### ISSUE TITLE
Error nach Anpassung des ToDoControllers

### ISSUE THREAD

**Issue by Phil1991** [MicrosoftDocs/azure-docs.de-de#105]
remote: An error has occurred during web site deployment.
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8ff46628-b5dc-8b02-02b6-8f510d8059b0
* Version Independent ID: 24d09b70-d144-d152-ac5a-c49219a5d8e8
* Content: [Umfassendes Authentifizieren und Autorisieren von Benutzern in Azure App Service](https://docs.microsoft.com/de-de/azure/app-service/app-service-web-tutorial-auth-aad#create-azure-resources)
* Content Source: [articles/app-service/app-service-web-tutorial-auth-aad.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/app-service/app-service-web-tutorial-auth-aad.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by DavidPrio** [comment]
Hallo, @Phil1991 , 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #10573](https://github.com/MicrosoftDocs/azure-docs/issues/10573) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @Phil1991, 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/10573. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
