### ISSUE TITLE
New tool to view Storage Tables on iOS

### ISSUE THREAD

**Issue by RoSchmi** [MicrosoftDocs/azure-docs.de-de#110]
According to your encouragement to inform about new tools to work with Azure Storage services I want to inform about my App AzureTabStorClient which can be used to view Azure Storage Tables on iOS devices. See more details at: https://azuretabstorclient.wordpress.com/

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 08d5d605-63a1-1388-59b9-2ec6d5b40766
* Version Independent ID: 11230eca-a134-fa35-63d8-7b195f0ca37a
* Content: [Tools für das Arbeiten mit Azure Storage](https://docs.microsoft.com/de-de/azure/storage/common/storage-explorers)
* Content Source: [articles/storage/common/storage-explorers.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/storage/common/storage-explorers.md)
* Service: **storage**
* GitHub Login: @dineshmurthy
* Microsoft Alias: **dineshmurthy**

**Comment by gosali** [comment]
Hello, @RoSchmi , 

 Thank you for your feedback. 

  

We are actively reviewing your comments and will get back to you soon. 

@SunnyDeng Could you please look this feedback? 

Kind regards, 

Microsoft DOCS International Team

**Comment by RoSchmi** [comment]
Thanks for your friendly reply. I’m sorry that I took the wrong feedback channel. Of course you can close this “issue”.
