### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by nnamedieh** [MicrosoftDocs/azure-docs.de-de#113]
Hi everybody, thanks for this well structured doc! Beside this, I would like to know if there's any additional charge when enabling the accerlated networking feature, because I didn't find anything about pricing.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e4be8e45-460a-fab4-519b-32d83382005c
* Version Independent ID: 36a002a6-5813-da00-0a57-068eeaf491cf
* Content: [Erstellen virtueller Azure-Computer mit beschleunigtem Netzwerkbetrieb](https://docs.microsoft.com/de-de/azure/virtual-network/create-vm-accelerated-networking-powershell)
* Content Source: [articles/virtual-network/create-vm-accelerated-networking-powershell.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/virtual-network/create-vm-accelerated-networking-powershell.md)
* Service: **virtual-network**
* GitHub Login: @gsilva5
* Microsoft Alias: **gsilva**

**Comment by gosali** [comment]
Hello, @nnamedieh , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
