### ISSUE TITLE
Please remember my language preferences

### ISSUE THREAD

**Issue by Krumelur** [MicrosoftDocs/azure-docs.de-de#114]
I'm located in Germany, my OS language and regional settings are set to German. Still, I would like to read online content in the language it was created in, because machine translations are worse than my English is. Using any Microsoft site, I always have to a) either scroll all the way to the bottom and change the language to English or b) have to flip the switch at the top saying "Auf Englisch lesen". 
It would be so convenient to store my preferences in a cookie and additionally have a setting in my profile.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fdd7dec4-a353-0ad5-2de3-1300ade6ad87
* Version Independent ID: 3f024fa1-7c94-a0a1-f72b-df98b33540a5
* Content: [Einfaches Experiment in Machine Learning Studio](https://docs.microsoft.com/de-de/azure/machine-learning/studio/create-experiment#feedback)
* Content Source: [articles/machine-learning/studio/create-experiment.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/machine-learning/studio/create-experiment.md)
* Service: **machine-learning**
* GitHub Login: @heatherbshapiro
* Microsoft Alias: **hshapiro**

**Comment by gosali** [comment]
Hello, @Krumelur , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  
CC: @SunnyDeng 
Kind regards, 
Microsoft DOCS International Team

**Comment by SunnyDeng** [comment]
@bodhigautam the customer request :"It would be so convenient to store my preferences in a cookie and additionally have a setting in my profile.", it needs site to support, can you please check?
