### ISSUE TITLE
How to get the authorization code for client-directed flow

### ISSUE THREAD

**Issue by philippschaefer4** [MicrosoftDocs/azure-docs.de-de#116]
It is mentioned here, that to do Server-to-Server authentication your "Client code signs user in directly with provider's SDK and receives an authentication token", that is then passed to the apps login-endpoint which then returns an actual access token which then can be used for further requests. 
I seem not to be able to find out how to get that "authentication token" (sometimes it is also called authorization code or grant) from google, using a "provider SDK". I work in Python. I found 2 possible SDK-candidates: google-auth and oauth2client (I think the latter is deprecated). But I can't make heads or tails of it.
I reckoned that you would just authenticate somehow with email and password (or perhaps with a service account). But I can't find any instructions for Azure+Python+GooglePlus.
Can somebody help?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 13176d24-57e1-33bb-1948-a086df502dca
* Version Independent ID: 1c15986a-adf6-6f99-72b4-e2a351d0c15e
* Content: [Authentifizierung und Autorisierung in Azure App Service](https://docs.microsoft.com/de-de/azure/app-service/app-service-authentication-overview)
* Content Source: [articles/app-service/app-service-authentication-overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/app-service/app-service-authentication-overview.md)
* Service: **app-service**
* GitHub Login: @mattchenderson
* Microsoft Alias: **mahender**

**Comment by LisandroSu** [comment]
Hello, @philippschaefer4 , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hi @SunnyDeng 

can you check on this issue?

Thanks!

**Comment by LisandroSu** [comment]
Hello, @philippschaefer4 
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
