### ISSUE TITLE
feedack to behavior of documentation page

### ISSUE THREAD

**Issue by wolfma61** [MicrosoftDocs/azure-docs.de-de#117]
For some unknown reason the documentation is showing in German (I'm German, but pretty much all my configuration settings on the machine are for 'english')

I can use the switch 'read text in english', which works and displayed the text in english.
The table of contents on the left and the contents of the article (on the right) are still in German.
What magic steps do I have to take to display everything in English?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d1276d74-d782-0ce6-2068-c498567784c2
* Version Independent ID: ef182604-da96-3aec-38c7-5c2adc15f47c
* Content: [Cognitive Services-Sprach-SDK – Lizenz - Microsoft Cognitive Services](https://docs.microsoft.com/de-de/azure/cognitive-services/speech-service/license)
* Content Source: [articles/cognitive-services/Speech-Service/license.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/cognitive-services/Speech-Service/license.md)
* Service: **cognitive-services**
* GitHub Login: @wolfma61
* Microsoft Alias: **wolfma**

**Comment by gosali** [comment]
Hello, @wolfma61 , 

Thank you for your feedback. 
We are actively reviewing your comments and will get back to you soon. 

Have you tried to open the English website?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/license 

Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @wolfma61 

You can also change the locale of the site in the bottom left corner of the page.

Regards,
Microsoft DOCS International Team
