### ISSUE TITLE
Code still working

### ISSUE THREAD

**Issue by wernerzirkel** [MicrosoftDocs/azure-docs.de-de#119]
Hello all, I wonder if this code example is still runnning. I tried it for 8 hours, no chance to get it working. Local execution works fine on any computer, but on may Azure App is says 

Could not load file or assembly 'System.Web.WebPages.Razor, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 72d855c6-51fd-a1da-5c44-8b44658c0211
* Version Independent ID: 15c87b07-e89e-2b0c-6337-3940a5259101
* Content: [Erstellen einer ASP.NET-App in Azure mit SQL-Datenbank](https://docs.microsoft.com/de-de/azure/app-service/app-service-web-tutorial-dotnet-sqldatabase#feedback)
* Content Source: [articles/app-service/app-service-web-tutorial-dotnet-sqldatabase.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/app-service/app-service-web-tutorial-dotnet-sqldatabase.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by LisandroSu** [comment]
Hello, @wernerzirkel 
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
