### ISSUE TITLE
Schneller und einfacher Einstieg - aber dann keine weiter Hilfe :-(

### ISSUE THREAD

**Issue by FrankPfattheicher** [MicrosoftDocs/azure-docs.de-de#122]
Die Einrichtung ist schnell und einfach, das Ergebnis super.
Will man aber jetzt den internen Aufbau der Lösung erkunden ist keinerlei Hilfe/Dokumentation mehr vorhanden.
z.B.: Wo kann man das Dashboard anpassen???

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8349b90f-e898-67fa-b3ec-b24b19700afa
* Version Independent ID: 93cb94ce-e8bf-b3cf-deb9-cae1ef10e7c9
* Content: [Ausprobieren einer cloudbasierten IoT-Remoteüberwachungslösung in Azure](https://docs.microsoft.com/de-de/azure/iot-accelerators/quickstart-remote-monitoring-deploy)
* Content Source: [articles/iot-accelerators/quickstart-remote-monitoring-deploy.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/iot-accelerators/quickstart-remote-monitoring-deploy.md)
* Service: **iot-accelerators**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13244](https://github.com/MicrosoftDocs/azure-docs/issues/13244) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hallo, @FrankPfattheicher ,

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.
 
Deshalb verschieben wir dieses   Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/13244.

Vielen Dank, dass Sie eine   gute Qualität unserer Artikel gewährleisten.

Mit freundlichen Grüßen
das Microsoft DOCS   International Team
