### ISSUE TITLE
Attach enryted disk (from snapshot) to a new VM

### ISSUE THREAD

**Issue by kamellemann** [MicrosoftDocs/azure-docs.de-de#123]
Hi,
is there a workflow for the following situation:
- create snapshot from a Data-Disks of an encrypted vm
- attach the the disk from the previous snapshot to an existing, also encrypted vm
Thanks

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 75aaea98-a087-c6d0-61cd-4a2edab37be5
* Version Independent ID: 6a2fa1ec-fadc-2d1c-2ab3-8ded33843414
* Content: [Azure Disk Encryption FAQ](https://docs.microsoft.com/de-de/azure/security/azure-security-disk-encryption-faq)
* Content Source: [articles/security/azure-security-disk-encryption-faq.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/security/azure-security-disk-encryption-faq.md)
* Service: **security**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@kamellemann I will check on this scenario for you. Is there a specific OS that you are targeting for this?

**Comment by kamellemann** [comment]
@mestew Thank´s for your fast response. OS ist Windows Server 2016.

**Comment by mestew** [comment]
@kamellemann Unfortunately, Azure Disk Encryption does not support that workflow at this time.  It does sound like a great [Azure Feedback item](https://feedback.azure.com/forums/216840-security-and-compliance) though! 
#please-close
