### ISSUE TITLE
B2B and SharePoint sharing: Different guest accounts?

### ISSUE THREAD

**Issue by ralphgoebel** [MicrosoftDocs/azure-docs.de-de#124]
Hello,
thanks for the good documentation :)
When I 
a) invite users using B2B and
b) invite external users using the share feature in SharePoint (users are not in my directory yet)

Is there a difference between these accounts? Both have userType = "Guest". We have invited users in the past using the share feature in SharePoint and now want to exclusively use B2B invitation. So I am wondering if we need to re-invite all the existing users.

Thanks and kind regards

Ralph

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1f8cb0a2-6df6-06d6-8cda-df18c0b2f32f
* Version Independent ID: e452da86-6fd9-0919-2f87-74a196b72c43
* Content: [Was ist die Azure Active Directory B2B-Zusammenarbeit?](https://docs.microsoft.com/de-de/azure/active-directory/b2b/what-is-b2b)
* Content Source: [articles/active-directory/b2b/what-is-b2b.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/active-directory/b2b/what-is-b2b.md)
* Service: **active-directory**
* GitHub Login: @twooley
* Microsoft Alias: **twooley**

**Comment by LisandroSu** [comment]
Hello, @ralphgoebel , 
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
