### ISSUE TITLE
Cannot install IoT Edge Extensions

### ISSUE THREAD

**Issue by philippschaefer4** [MicrosoftDocs/azure-docs.de-de#125]
Hello,

I'm trying to setup a raspberry pi with Raspbian Stretch as IoT-Edge-Device. I started with a clean install via Noobs. Then I followed the instructions here https://docs.microsoft.com/de-de/cli/azure/install-azure-cli-apt?view=azure-cli-latest .
This went fine so far, but when I then wanted to install the IoT Edge Extensions via "az extension add --name azure-cli-iot-ext" the install fails: "Pip failed with status code 2". 

In the (quiet extensive) debug logs there are endless entries of "skipping link https://this-and-that.org/somepackage [...] it is not compatible with this python". Could the problem be my python installation. I don't really know how to interpret this. I have Python 2.7 as well as 3.5 installed.

Another thing in the logs is that it says:  "Linux distro check: Found in list file: stretch" but also "Linux distro check: Reported by API: None". And after that it suggests: "If command fails, install the appropriate package for your distribution or change the above file accordingly."
I assume that the Azure CLI is meant by API. So do I have to configure the CLI before I install any extension, or something like that? Or did I miss something when installing the actual azure cli? Because "stretch" is definitely the correct version name as given by "lsb_release -cs". The question is, why does the API report "None" as distro.

Or is Raspbian Stretch just not identical to Debian Stretch and for that reason the compatibility is simply not given and I have to manually install the CLI?

Many thanks and praises in advance for any help.
Philipp

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e2289383-6ce2-a036-c710-7d1fad6e1700
* Version Independent ID: 3b902941-0876-17c3-3f0b-a4b7f7770531
* Content: [Schnellstart für Azure IoT Edge + Linux](https://docs.microsoft.com/de-de/azure/iot-edge/quickstart-linux)
* Content Source: [articles/iot-edge/quickstart-linux.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/iot-edge/quickstart-linux.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by philippschaefer4** [comment]
I just noticed that the instruction how to install Azure CLI set the repository architecture to "amd64". But Raspberry Pi has an ARM-Architecture, right? So could it be that I just keep installing the wrong binaries?
The question remains: how would I set the architecture to ARM. I already tried "[arch=arm]", but that didn't work.

**Comment by gosali** [comment]
Hello, @philippschaefer4 , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.  

If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
