### ISSUE TITLE
Didn't find a sample receiving C2D messages

### ISSUE THREAD

**Issue by FrankPfattheicher** [MicrosoftDocs/azure-docs.de-de#127]
I successfully implemented an Edge module but have no clue how to receive C2D messages and/or method invokes.

Searched all samles - nothing about this (C#).

Found the following Note: 
Currently IoT Edge only supports send messages into one module from another module, direct C2D messages doesn't work.

Now i am not shure if it is supported or not.
The feature overvie points out it is availabe in "Standard" IoT-Hub i am using.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c98493ac-edae-593a-2fd8-d4e25787c6ef
* Version Independent ID: 3235ee03-677f-9e21-6464-471743536234
* Content: [Debuggen von C#-Modulen für Azure IoT Edge](https://docs.microsoft.com/de-de/azure/iot-edge/how-to-develop-csharp-module)
* Content Source: [articles/iot-edge/how-to-develop-csharp-module.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/iot-edge/how-to-develop-csharp-module.md)
* Service: **iot-edge**
* GitHub Login: @shizn
* Microsoft Alias: **xshi**

**Comment by LisandroSu** [comment]
Hello, @FrankPfattheicher, 
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
