### ISSUE TITLE
Failed to download VPN device configuration template

### ISSUE THREAD

**Issue by nnamedieh** [MicrosoftDocs/azure-docs.de-de#128]
Hi all, 
unfortunately I ran into an error when I tried to download any VPN device configuration template from the "Connection". I copied and pasted all the powershell commands mentioned in this documentation to create all necessary services, but when I want to download the VPN device configuration it shows the following error:

"File download error: Failed to dynamically fetch target download uri."

Looking into the activity log the error is 

"Error code IpsecPolicyNotSupportedOnVpnDevice"

But I actually don't configure any ipsec policy on the VPN gateway, just copied the instructions mentioned in this doc. 

I figured out that when I disable BGP in the Connection, I am able to download any vpn device configuration template.

Can anybody help me to figure out what's the problem in this case and why I am only able to download the vpn device configuration template when it's disabled in the connection?

Thank you very much,

Daniel

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 27b300f3-7b57-0772-9a36-6448a56b3d23
* Version Independent ID: 959e9abd-3033-df6c-cb30-8277b0acbf0d
* Content: [Konfigurieren von Aktiv/Aktiv-S2S-VPN-Verbindungen für VPN Gateways: Azure Resource Manager: PowerShell](https://docs.microsoft.com/de-de/azure/vpn-gateway/vpn-gateway-activeactive-rm-powershell)
* Content Source: [articles/vpn-gateway/vpn-gateway-activeactive-rm-powershell.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/vpn-gateway/vpn-gateway-activeactive-rm-powershell.md)
* Service: **vpn-gateway**
* GitHub Login: @yushwang
* Microsoft Alias: **yushwang, cherylmc**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13816](https://github.com/MicrosoftDocs/azure-docs/issues/13816) via [**ZenHub**](https://www.zenhub.com/)
