### ISSUE TITLE
Limitations of Web Services deployed via Jupyter Notebook

### ISSUE THREAD

**Issue by philippschaefer4** [MicrosoftDocs/azure-docs.de-de#132]
Hi, I really like the jupyter notebook way of publishing a model as a Web Service. I like it even better than the GUI. But I seem to run into the same problems with both ways, when I try certain 'memory-hungry' predictions. So my question is: what are the limits especially for memory in such a web service.
More specifically I would like to know more about the inner workings of the notebook/webservice-thing that is created. It seems to be possible to create and train a model, say from sklearn, and then use it in the web service function. So the data from the notebook-memory (the weights and stuff from the model) seem to persist in the webservice. How far does this go. Are the model parameters just copied during the creation of the service? Or has the service access to the notebooks memory?
I ask this because in some cases I need to access whole datasets during the web service call. For example for comparisons. But when I call the datasets in the service-function via a Workspace-Object just like I get it outside the function, I get a 500-error. When I comment it out, everything is fine. It's definitely the access to a dataset. So the last question is: how do I access a dataset from inside the web service function. Or is this more or less impossible because of memory limitations.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9c016ab8-9efe-c790-e0f6-8ae38b6b4931
* Version Independent ID: 8e61b0ff-34b6-8137-1e4c-c4e958d8046a
* Content: [Jupyter-Notebooks im Azure AI-Katalog](https://docs.microsoft.com/de-de/azure/machine-learning/studio/gallery-jupyter-notebooks)
* Content Source: [articles/machine-learning/studio/gallery-jupyter-notebooks.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/machine-learning/studio/gallery-jupyter-notebooks.md)
* Service: **machine-learning**
* GitHub Login: @heatherbshapiro
* Microsoft Alias: **hshapiro**

**Comment by LisandroSu** [comment]
Hello, @philippschaefer4 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
