### ISSUE TITLE
Batch Script Encoding

### ISSUE THREAD

**Issue by SFuhrmann** [MicrosoftDocs/azure-docs.de-de#133]
A hint on the right encoding of the setup.bat file would be nice.

I ran into the issue that the PowerShell script was not executed. In the log file on the local Service Fabric Cluster Node it said "powershell.exe was not found" etc. I spent a lot of time trying to find out why the SF Node did not find the powershell.

The problem was: The setup.bat was encoded as UTF-8 with BOM. These were interpreted by the command line as well, resulting in the wrong command. I could only figure this out when I started the setup.bat manually and have a look at the output there, because in textfile editors the BOM were interpreted correctly again.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3ac102a5-e9ad-0046-f217-446f1ad263c5
* Version Independent ID: a47523e2-0c30-dee4-0037-5f58836fa37f
* Content: [Hinzufügen eines HTTPS-Endpunkts zu einer Service Fabric-App in Azure mithilfe von Kestrel](https://docs.microsoft.com/de-de/azure/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint)
* Content Source: [articles/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint.md)
* Service: **service-fabric**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #15928](https://github.com/MicrosoftDocs/azure-docs/issues/15928) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @SFuhrmann 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/15928.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
