### ISSUE TITLE
Sign-on URL/Reply Url seems to be incorrect in Documentation

### ISSUE THREAD

**Issue by jhueppauff** [MicrosoftDocs/azure-docs.de-de#136]
I tried to set this up this way described by the Documentation.
But for me it seems I have to configure "https://login.microsoftonline.com/te/{tenant}.onmicrosoft.com/oauth2/authresp" as Reply Url as I got an Error Message which suggested that.

Can you please validate the Information in the documentation?

Thanks
Julian

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bac6db2d-bff9-cbcf-d522-966ed17ea27f
* Version Independent ID: 91e3eeb7-8602-9e26-21c3-1fa70d03a354
* Content: [Hinzufügen eines Azure AD-Anbieters mithilfe integrierter Richtlinien in Azure Active Directory B2C](https://docs.microsoft.com/de-de/azure/active-directory-b2c/active-directory-b2c-setup-oidc-azure-active-directory)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-setup-oidc-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/active-directory-b2c/active-directory-b2c-setup-oidc-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @davidmu1
* Microsoft Alias: **davidmu**

**Comment by jhueppauff** [comment]
this seems also to affect the other (checked with github and microsoft identity provider) Identity Provider.
Should I open also an issue there, or is this sufficent?

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #16046](https://github.com/MicrosoftDocs/azure-docs/issues/16046) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @jhueppauff 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/16046.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
