### ISSUE TITLE
"Unable to query host" when profiling

### ISSUE THREAD

**Issue by Variour** [MicrosoftDocs/azure-docs.de-de#137]
I'm having some trouble getting the profiling data from one of my Hyper-V hosts.
I have successfully enabled PSRemoting on the host and can connect with Enter-PSSession. I have added the Hyper-V hosts hostname to the assement tool machines trusted hosts list and the assesment tool machines hostname to the hyper-vs trusted hosts list.
The VM list generation works fine. When I start the data collection process with
```
.\ASRDeploymentPlanner.exe -Operation StartProfiling -Virtualization Hyper-V -VMListFile C:\Users\<USERNAME>\Desktop\profiling_test\VMListFile_2018-10-04_09-41-33.txt -Directory "C:\Users\<USERNAME>\Desktop\profiling_test\201810041019" -NoOfMinutesToProfile 30 -User "<DOMAIN>\<USERNAME>"
```
everything works generally fine as well. The tool is running, connects to the server, shows the machines that are powered off. It also creates the files VMdetailList.xml and PhysicalVolumeDetail.xml. After that the profiling begins and it looks like everything is running smoothly but the log shows the following five messages every time the server is queried:
```
10/04/2018 10:21:03:Attempting Data Collection from <hostname> at 04.10.2018 08:21:03
10/04/2018 10:21:03:Connected to host <hostname> at 04.10.2018 10:21:03
10/04/2018 10:21:06:Unable to Query host <hostname> at 04.10.2018 10:21:06
10/04/2018 10:21:06:Collecting Data from <hostname> at 04.10.2018 08:21:03
10/04/2018 10:21:06:No Counters found for <hostname> at 04.10.2018 08:21:03
```
(By the way, some messages show the local time UTC+2 while some show UTC, not consistent)

The hyper-v host is running Windows Server 2012R2.
The profiling machine is running Windows Server 2016 1607.
I have other Hyper-V hosts with the same OS where the data collection works without problems.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fbf128d7-d77d-12dd-f497-98d39c8d9d01
* Version Independent ID: 10d01522-5838-982d-d5fd-c796509d90b1
* Content: [Azure Site Recovery-Bereitstellungsplaner für „Hyper-V zu Azure“](https://docs.microsoft.com/de-de/azure/site-recovery/hyper-v-deployment-planner-run)
* Content Source: [articles/site-recovery/hyper-v-deployment-planner-run.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/site-recovery/hyper-v-deployment-planner-run.md)
* Service: **site-recovery**
* GitHub Login: @nsoneji
* Microsoft Alias: **nisoneji**

**Comment by LisandroSu** [comment]
Hello, @Variour ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by Variour** [comment]
Hi,

thanks for your reply!
Just wanted to say that i figured the problem out and share my solution.

I had to reset the performance counter registry settings on the affected hyper-v host, which i did with the command
`lodctr /r`

If there is a troubleshooting section in the docs this might be added, otherwise if someone finds this via google they will at least have my solution.
