### ISSUE TITLE
VPN gateway routing issues

### ISSUE THREAD

**Issue by nnamedieh** [MicrosoftDocs/azure-docs.de-de#139]
Hi all,

I have a problem to reach my vm in Azure East US 2.

My setup is the following:
Site to Site VPN between OnPrem and Azure Westeurope. In Westeurope, there's a Vnet, which is connected through Vnet to Vnet connection (site to site vpn and vnet to vnet connection is the same azure gateway) with Vnet in East US 2. In this Vnet in East US 2, there's a vm I want to be able to reach. I supposed to be able to accomplish this with UDRs, but I'm actually not able to get it run.

Does anyone know what to configure to be able to reach this vm in east us 2 over vpn S2S from onprem to westeurope vnet and from there over Vnet to Vnet connection to east us 2?

Thank you :)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 38bd69ac-a1b5-a401-184d-37b55188a7c4
* Version Independent ID: ef976d45-36eb-8a32-4b29-ae03412165d2
* Content: [Routing von Datenverkehr für virtuelle Azure-Netzwerke](https://docs.microsoft.com/de-de/azure/virtual-network/virtual-networks-udr-overview)
* Content Source: [articles/virtual-network/virtual-networks-udr-overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/virtual-network/virtual-networks-udr-overview.md)
* Service: **virtual-network**
* GitHub Login: @jimdial
* Microsoft Alias: **jdial**

**Comment by LisandroSu** [comment]
Hello, @nnamedieh ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
