### ISSUE TITLE
Valid OAuth Redirect

### ISSUE THREAD

**Issue by zweckj** [MicrosoftDocs/azure-docs.de-de#141]
The link (14.) for the OAuth Redirect should be https://login.microsoftonline.com/te/{tenantname}/oauth2/resp

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: aeb73901-3320-4d53-767c-bfd03b3b0354
* Version Independent ID: 404e18f1-d6da-5654-3e68-8e888e11433e
* Content: [Einrichten der Registrierung und Anmeldung mit einem Facebook-Konto mithilfe von Azure Active Directory B2C](https://docs.microsoft.com/de-de/azure/active-directory-b2c/active-directory-b2c-setup-fb-app)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-setup-fb-app.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/active-directory-b2c/active-directory-b2c-setup-fb-app.md)
* Service: **active-directory**
* GitHub Login: @davidmu1
* Microsoft Alias: **davidmu**

**Comment by LisandroSu** [comment]
Hello, @zweckj 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @zweckj
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/azure/active-directory-b2c/active-directory-b2c-setup-fb-app.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
