### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by ithahn** [MicrosoftDocs/azure-docs.de-de#151]
Installieren und Konfigurieren von Microsoft Monitoring Agent: https://docs.microsoft.com/de-de/log-analytics/log-analytics-concept-hybrid.md#install-and-configure-agent

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c9e7b53a-a644-3ada-8363-ae4edc62f503
* Version Independent ID: a5567355-2edb-d722-3a08-2217d33d9510
* Content: [Grundlegende Informationen zu den Agent-Überprüfungsergebnissen in der Azure-Updateverwaltung](https://docs.microsoft.com/de-de/azure/automation/troubleshoot/update-agent-issues)
* Content Source: [articles/automation/troubleshoot/update-agent-issues.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/automation/troubleshoot/update-agent-issues.md)
* Service: **automation**
* GitHub Login: @georgewallace
* Microsoft Alias: **gwallace**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #19525](https://github.com/MicrosoftDocs/azure-docs/issues/19525) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @<contributor's GITHUB name>, 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/19525. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
