### ISSUE TITLE
what is Role ?

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/azure-docs.de-de#159]
nothing is mentioned about the role in the List entity. What is its purpose?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3578db8f-e411-b0e6-4990-dd3c49f6a41f
* Version Independent ID: 21e19094-e487-a942-13f6-4fc1f0129feb
* Content: [Tutorial 4: Genaue Textübereinstimmungen – LUIS-Listenentität - Azure Cognitive Services](https://docs.microsoft.com/de-de/azure/cognitive-services/luis/luis-quickstart-intent-and-list-entity)
* Content Source: [articles/cognitive-services/LUIS/luis-quickstart-intent-and-list-entity.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/cognitive-services/LUIS/luis-quickstart-intent-and-list-entity.md)
* Service: **cognitive-services**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by aldonetti** [comment]
Hi @MarcelMeurer do you have any input on this, please? thanks!!

**Comment by MarcelMeurer** [comment]
Hallo @vivekjainAco. Was meinst du mit Rolle. Soweit ich sehe, ist die Rolle keine Eigenschaft der Entitätenliste. Oder bezieht sich die Frage auf den Sinn der Liste (mit den Entitäten)?

**Comment by CeciAc** [comment]
Hallo, @vivekjainAco 
Wir möchten nochmals auf unseren vorherigen Kommentar zurückkommen. Wir benötigen weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern?
Mit freundlichen Grüßen
Microsoft DOCS International Team

**Comment by diberry** [comment]
@vivekjainAco Thank you for asking this question. This is a good question and not clearly called out in the tutorial. The tutorials are being revised at this time and this will be a good thing to clarify. Some of the roles are easier to determine how to use them. A role, at this time, is only useful with patterns. So a role with a list means that the list and its items could have multiple contexts based on the utterance template in a pattern. I will look for a good example.

**Comment by diberry** [comment]
#please-close
