### ISSUE TITLE
Supported SAML authentication methods for Azure AD

### ISSUE THREAD

**Issue by saschagottfried** [MicrosoftDocs/azure-docs.de-de#160]
Documentation about [Single Sign-On SAML protocol](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol) states that [only a single value, `urn:oasis:names:tc:SAML:2.0:ac:classes:Password`, is supported by Azure AD](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol#requestauthncontext).

> The RequestedAuthnContext element specifies the desired authentication methods. It is optional in AuthnRequest elements sent to Azure AD. Azure AD supports only one AuthnContextClassRef value: urn:oasis:names:tc:SAML:2.0:ac:classes:Password.

While working with SAML-based SSO enterprise apps I experienced successful logins with authentication method `urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport`. 

Sample SAML request

```xml
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_f2f53b14adcc7953b7876da9d4111904a15fe21b" Version="2.0" IssueInstant="2018-12-12T10:51:47Z" Destination="https://login.microsoftonline.com/bbb4fb3f-6d53-4a76-9cbb-a5e3a825c924/saml2" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://eu.rescale.com/saml2/hhp-berlin/acs/" ForceAuthn="true">
    <saml:Issuer>https://eu.rescale.com/saml2/hhp-berlin/</saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" AllowCreate="true"/>
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

Please review the docs about supported values for SAML request element `AuthnContextClassRef` !
Thanks.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 62bb99a4-4092-0202-48bf-4e61ee424faf
* Version Independent ID: a066de9a-42fb-2fcc-683d-2ffdc45fdf3d
* Content: [Azure-SAML-Protokoll für einmaliges Anmelden](https://docs.microsoft.com/de-de/azure/active-directory/develop/single-sign-on-saml-protocol)
* Content Source: [articles/active-directory/develop/single-sign-on-saml-protocol.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/active-directory/develop/single-sign-on-saml-protocol.md)
* Service: **active-directory**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by saschagottfried** [comment]
Copy of https://github.com/MicrosoftDocs/azure-docs/issues/20550 due to initial submission from localized, german documentation.

**Comment by CeciAc** [comment]
Hello, @saschagottfried 
Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue # [https://github.com/MicrosoftDocs/azure-docs/issues/20550]. For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
