### ISSUE TITLE
Why the file upload is not supported in the replace knowledgebase API

### ISSUE THREAD

**Issue by vivekjainAco** [MicrosoftDocs/azure-docs.de-de#161]
I want to replace the existing knowledge base, and I have a new KB base in my excel file which I want to use to replace the existing QnA. 

Its strange a bit that replaces knowledge base API does not support URL parameter, but only QnA List. I tried it on the API console. Can someone update the API so that would be more useful then.
#

Thanks in advance 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b442bbc5-80c1-c463-ddc8-9ddc6453b827
* Version Independent ID: 64467bb5-b053-7720-8ffe-9dcc68024f05
* Content: [REST-API (Version 4) – C# – QnA Maker - Azure Cognitive Services](https://docs.microsoft.com/de-de/azure/cognitive-services/qnamaker/quickstarts/csharp#replace-knowledge-base)
* Content Source: [articles/cognitive-services/QnAMaker/Quickstarts/csharp.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/cognitive-services/QnAMaker/Quickstarts/csharp.md)
* Service: **cognitive-services**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by CeciAc** [comment]
Hello, @vivekjainAco 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
