### ISSUE TITLE
Autocomplete is reversed

### ISSUE THREAD

**Issue by SebastianAtWork** [MicrosoftDocs/azure-docs.de-de#246]
https://docs.microsoft.com/de-de/azure/azure-functions/functions-bindings-service-bus#hostjson-settings autocomplete is exactly the opposite of what it actually does in functions 2.0

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0440205f-adcc-0fc5-3adb-db4dbe1d1292
* Version Independent ID: 14ad1300-590c-8102-6887-366078e1882a
* Content: [Azure Service Bus-Bindungen für Azure Functions](https://docs.microsoft.com/de-de/azure/azure-functions/functions-bindings-service-bus#hostjson-settings)
* Content Source: [articles/azure-functions/functions-bindings-service-bus.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/azure-functions/functions-bindings-service-bus.md)
* Service: **azure-functions**
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by CeciAc** [comment]
Hello, @SebastianAtWork 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #23298](https://github.com/MicrosoftDocs/azure-docs/issues/23298) via [**ZenHub**](https://www.zenhub.com/)
