### ISSUE TITLE
Step 10 not clear

### ISSUE THREAD

**Issue by Eichi87** [MicrosoftDocs/azure-docs.de-de#254]
The whole tutorial is pretty straightforward except for the last step.
Where do you pass the token?

I use the authentification header presented during the "Tutorial: Create an Azure Time Series Insights single-page web app", which looks like this:
```
        // START: AUTHENTICATION RELATED CODE USING ADAL.JS
            // Set up ADAL
            var authContext = new AuthenticationContext({
                clientId: '***',
                postLogoutRedirectUri: 'https://***.azurewebsites.net',
                cacheLocation: 'localStorage'
            });
            
            if (authContext.isCallback(window.location.hash)) {
            
                // Handle redirect after token requests
                authContext.handleWindowCallback();
                var err = authContext.getLoginError();
                if (err) {
                    // TODO: Handle errors signing in and getting tokens
                    document.getElementById('api_response').textContent = err;
                    document.getElementById('loginModal').style.display = "block";
                }
            
            } else {
                var user = authContext.getCachedUser();
                if (user) {
                    document.getElementById('username').textContent = user.userName;
                    
                } else {
                    document.getElementById('username').textContent = 'Not signed in.';
                }
            }
            
            authContext.getTsiToken = function(){
                document.getElementById('api_response2').textContent = 'Getting tsi token...';
                
                // Get an access token to the Microsoft TSI API
                var promise = new Promise(function(resolve,reject){
                    authContext.acquireToken(
                    'https://api.timeseries.azure.com/',
                    function (error, token) {
            
                        if (error || !token) {
                            // TODO: Handle error obtaining access token
                            document.getElementById('api_response').textContent = error;
                            document.getElementById('loginModal').style.display = "block";
                            document.getElementById('api_response2').textContent = '';
                            return;
                        }
            
                        // Use the access token
                        document.getElementById('api_response').textContent = '';
                        document.getElementById('api_response2').textContent = '';
                        document.getElementById('loginModal').style.display = "none";
                        resolve(token);
                        }
                    );
                });
                
                return promise;
            }
        // END: AUTHENTICATION RELATED CODE USING ADAL.JS
```

The Web App has every permission i can think of.

Using Postman I can call a token and the TSI data. Still the Web App doesn't work.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2f1c1d09-3921-2730-1b7b-2cc2d601bdd4
* Version Independent ID: 71c02dae-2cb2-07c2-dfa4-96990fee3389
* Content: [Informationen zum Authentifizieren und Autorisieren mithilfe der API in Azure Time Series Insights](https://docs.microsoft.com/de-de/azure/time-series-insights/time-series-insights-authentication-and-authorization)
* Content Source: [articles/time-series-insights/time-series-insights-authentication-and-authorization.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/time-series-insights/time-series-insights-authentication-and-authorization.md)
* Service: **time-series-insights**
* GitHub Login: @ashannon7
* Microsoft Alias: **anshan**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24002](https://github.com/MicrosoftDocs/azure-docs/issues/24002) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @Eichi87 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/24002.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
