### ISSUE TITLE
Sample for set-backend-service / servicefabric is incorrect

### ISSUE THREAD

**Issue by KaiWalter** [MicrosoftDocs/azure-docs.de-de#256]
This is not correct
    &lt;set-backend-service
        backend-id="servicefabric"
        sf-service-instance-name="service-name"
        sf-resolve-condition="@(context.LastError?.Reason == 'BackendConnectionFailure')" /&gt;

the string value inside the policy expression needs to be enclosed with double quotes:
    &lt;set-backend-service
        backend-id="servicefabric"
        sf-service-instance-name="service-name"
        sf-resolve-condition="@(context.LastError?.Reason == "BackendConnectionFailure")" /&gt;

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 93a7a08f-2b74-eece-b263-03ab211cf805
* Version Independent ID: 73bbdc61-d007-687f-9f78-a0e5a9de1f28
* Content: [Integrieren von API Management in Service Fabric in Azure](https://docs.microsoft.com/de-de/azure/service-fabric/service-fabric-tutorial-deploy-api-management#feedback)
* Content Source: [articles/service-fabric/service-fabric-tutorial-deploy-api-management.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/service-fabric/service-fabric-tutorial-deploy-api-management.md)
* Service: **service-fabric**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24190](https://github.com/MicrosoftDocs/azure-docs/issues/24190) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @KaiWalter 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/24190.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
