### ISSUE TITLE
Access IoT Blob Storage with Data Factory v2

### ISSUE THREAD

**Issue by maecky** [MicrosoftDocs/azure-docs.de-de#257]
Is it possible to integrate IoT Blob Storage into Data Factory pipelines? If so, can you please provide an example in the documentation?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 07a44a28-a19c-f68e-167c-5e8ad91605e0
* Version Independent ID: 33eacdff-4f0a-c543-d8f9-e7b208bab015
* Content: [Speichern von Blockblobs auf Geräten – Azure IoT Edge](https://docs.microsoft.com/de-de/azure/iot-edge/how-to-store-data-blob)
* Content Source: [articles/iot-edge/how-to-store-data-blob.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/iot-edge/how-to-store-data-blob.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by LisandroSu** [comment]
Hello, @maecky 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
