### ISSUE TITLE
RBAC-enabled cluster support

### ISSUE THREAD

**Issue by Turil** [MicrosoftDocs/azure-docs.de-de#263]
Hi,
the FAQ states that RBAC enabled clusters are not supported by Azure Monitor yet, but on the other hand https://docs.microsoft.com/de-de/azure/azure-monitor/insights/container-insights-live-logs already has instructions how to enable live logs for RBAC clusters. This requires Azure Monitor to run.
Can you provide an estimate when RBAC clusters will be fully supported?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f1676f3c-3f68-68d6-2499-1961c320ca36
* Version Independent ID: 8a922f14-09ca-c207-63df-3acf106d81be
* Content: [Häufig gestellte Fragen zu Azure Monitor für Container](https://docs.microsoft.com/de-de/azure/azure-monitor/insights/container-insights-faq)
* Content Source: [articles/azure-monitor/insights/container-insights-faq.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/azure-monitor/insights/container-insights-faq.md)
* Service: **azure-monitor**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by CeciAc** [comment]
Hello, @Turil 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
