### ISSUE TITLE
Wrong show-connection-string parameter

### ISSUE THREAD

**Issue by maxstreifeneder** [MicrosoftDocs/azure-docs.de-de#265]
Liebe Microsoft-Kollegen,

Der Befehl in **Schritt 3** "Registrieren eines Gerätes" funktioniert so leider nicht, der Parameter-Name hat sich scheinbar geändert. 

Im Dokument: 
az iot hub show-connection-string --hub-name YourIoTHubName --output table

Richtigerweise: 
az iot hub show-connection-string --name YourIoTHubName --output table

![image](https://user-images.githubusercontent.com/36535298/54447564-12331380-474a-11e9-83f2-e8657a7b7740.png)

Grüße,
Maxi

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0f1d1d66-4cc5-82ec-b4e5-1c88662c85ac
* Version Independent ID: 82007f25-a1ec-832f-a431-c416a1de42a0
* Content: [Schnellstart: Senden von Telemetriedaten an Azure IoT Hub (Node.js)](https://docs.microsoft.com/de-de/azure/iot-hub/quickstart-send-telemetry-node#feedback)
* Content Source: [articles/iot-hub/quickstart-send-telemetry-node.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/iot-hub/quickstart-send-telemetry-node.md)
* Service: **iot-hub**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #27346](https://github.com/MicrosoftDocs/azure-docs/issues/27346) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hallo, @maxstreifeneder 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/27346
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
