### ISSUE TITLE
Confluence SSO with Azure AD

### ISSUE THREAD

**Issue by kamellemann** [MicrosoftDocs/azure-docs.de-de#268]
Hi,

we´ve already implemented SSO with Azure AD for Confluence for our Test-Environment.
Everything is working fine and we just had to sync the metadata XML file from Azure AD.
Sins this week, we retrieve the following error from the "Microsoft Azure Active Directory single sign-on for Confluence": "More than 1 certificates received in federation metadata. Only one certificate should be present. Please contact Azure AD Admin."
We are not able to implement SSO in our live stage as the Plugin will not process in importing the XML.
Even our (running and working) test system is showing this error now (we discard any changes so that SSO is still working with this plugin).
https://www.microsoft.com/en-us/download/details.aspx?id=56503 

Thanks
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a45acbc6-caae-be6c-939e-55451831d03e
* Version Independent ID: 0d88f4ee-2ac5-1ad4-245b-b8c0752a7303
* Content: [Tutorial: Azure Active Directory-Integration mit Confluence SAML SSO by Microsoft](https://docs.microsoft.com/de-de/azure/active-directory/saas-apps/confluencemicrosoft-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/confluencemicrosoft-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/active-directory/saas-apps/confluencemicrosoft-tutorial.md)
* Service: **active-directory**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by kamellemann** [comment]
![SSO](https://user-images.githubusercontent.com/24431844/55161893-d72bd980-5166-11e9-980e-575024521e6a.png)

**Comment by CeciAc** [comment]
Hello, @kamellemann 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by jeevansd** [comment]
@kamellemann Can you please make sure that you only have one certficate in the Azure AD Confluence app? The plugin is expecting that you should not have even InActive certificate in Azure AD for the Confluence app. 

If you are still facing issues then please send out email to SaaSApplicationIntegrations@service.microsoft.com and then we will schedule the meeting with you.

**Comment by kamellemann** [comment]
@jeevansd Thank´s for your support. There is only one certificate present. Everything was workinf fine for our Test-System (even if this is showing the same error now). We´ve created a quite new enterprise application in azure ad for our live system.

**Comment by kamellemann** [comment]
![cert](https://user-images.githubusercontent.com/24431844/55381453-7ebc5980-5523-11e9-8d64-6de67c50c468.PNG)
