### ISSUE TITLE
Missing script to create SP

### ISSUE THREAD

**Issue by Lycrosa** [MicrosoftDocs/azure-docs.de-de#271]
Missing script to create SP

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 11bbaa44-52ed-33fd-d710-af73d3665ec9
* Version Independent ID: b11deb17-311c-3aa3-78a7-1f8cdc7e9e5e
* Content: [Azure Container Registry-Authentifizierung mit einem Dienstprinzipal](https://docs.microsoft.com/de-de/azure/container-registry/container-registry-auth-service-principal#feedback)
* Content Source: [articles/container-registry/container-registry-auth-service-principal.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/container-registry/container-registry-auth-service-principal.md)
* Service: **container-registry**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by Lycrosa** [comment]
nevermind, im blind. But I guess there is still an formating issue in this article, or is [!code-azurecli-interactiveacr-sp-role-assign] ment to mean something.

**Comment by CeciAc** [comment]
Hello, @Lycrosa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #28485](https://github.com/MicrosoftDocs/azure-docs/issues/28485) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Lycrosa 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/28485

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
