### ISSUE TITLE
Using custom model IDs does not work like explained

### ISSUE THREAD

**Issue by strohne** [MicrosoftDocs/azure-docs.de-de#273]
When using custom model IDs I get an error: 

> The request body is invalid: Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'models[0]', line 4, position 50.

Could you please explain how to correctly provide the model ID?

My payload example:

> {
> "name":"https://urltoblob.wav",
> "recordingsUrl":"https://urltoblob.wav",
> "models" : ["11111111-2222-3333-4444-55555555555"],
> "locale":"de-DE"
> }

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 73fb7e76-fb80-c420-2efe-e3ca3a27b749
* Version Independent ID: 07a42557-deb3-e4b3-3f14-f26a27be49c2
* Content: [Verwenden von Batch-Transkriptionen – Speech Services](https://docs.microsoft.com/de-de/azure/cognitive-services/speech-service/batch-transcription)
* Content Source: [articles/cognitive-services/Speech-Service/batch-transcription.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/cognitive-services/Speech-Service/batch-transcription.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @PanosPeriorellis
* Microsoft Alias: **panosper**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #28573](https://github.com/MicrosoftDocs/azure-docs/issues/28573) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @strohne

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/28573

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
