### ISSUE TITLE
Doppeldeutig in der Übersetzung

### ISSUE THREAD

**Issue by jgoedtke** [MicrosoftDocs/azure-docs.de-de#277]
Hier ist die Übersetzung aus dem englischen sehr missverständlich:
shared sollte mit geteilt, nicht mit freigegeben übersetzt werden.

Die Lösung „SAP HANA in Azure (große Instanzen)“ beruht auf nicht freigegebener Host- bzw. Bare-Metal-Hardware, die Ihnen zugewiesen ist.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 846460be-259d-ac90-f510-85dd5c8a798b
* Version Independent ID: 829e261c-2446-68d6-65a3-a1b0456ec43b
* Content: [Übersicht über SAP HANA in Azure (große Instanzen)](https://docs.microsoft.com/de-de/azure/virtual-machines/workloads/sap/hana-overview-architecture#feedback)
* Content Source: [articles/virtual-machines/workloads/sap/hana-overview-architecture.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/virtual-machines/workloads/sap/hana-overview-architecture.md)
* Service: **virtual-machines-linux**
* GitHub Login: @RicksterCDN
* Microsoft Alias: **saghorpa**

**Comment by CeciAc** [comment]
Hallo, @jgoedtke 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @jgoedtke
 
Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/azure/virtual-machines/workloads/sap/hana-overview-architecture#feedback
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
