### ISSUE TITLE
Download link to Log Parser broken

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/azure-docs.de-de#285]
@paule96 commented on [Wed Mar 06 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379)

Hi Microsoft,

[here](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#web-server-logs) is the link to "Log Paser" no longer working. Can we fix this? But I don't know the new link to the Log Parser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc316af-0d30-b449-a04f-3019b7a16bc1
* Version Independent ID: 01c4c435-fda9-374a-70b3-f1d7f13c7651
* Content: [Enable diagnostics logging for apps - Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#web-server-logs)
* Content Source: [articles/app-service/troubleshoot-diagnostic-logs.md](https://github.com/Microsoft/azure-docs/blob/master/articles/app-service/troubleshoot-diagnostic-logs.md)
* Service: **app-service**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

---

@BryanTrach-MSFT commented on [Wed Mar 06 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379#issuecomment-470222598)

@paule96 Thanks for the feedback! We are currently investigating and will update you shortly.

---

@Potapy4 commented on [Thu Mar 07 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379#issuecomment-470435510)

@paule96 I don't see any problems with the link - it's redirected to https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=24659

---

@paule96 commented on [Thu Mar 07 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379#issuecomment-470640711)

Hi @Potapy4,

I mean this link:

![image](https://user-images.githubusercontent.com/11291885/53979923-4c2f6480-410f-11e9-8e79-62893b39a3eb.png)

this redirect me to this url:
https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=24659=de-de

---

@BryanTrach-MSFT commented on [Sat Mar 09 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379#issuecomment-471146865)

@paule96 Just like @Potapy4 I do not encounter the issue. Clicking on "Log Parser" takes me to the proper link. I have provided the link that I am directed to below for your convience.

https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=24659

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

---

@paule96 commented on [Sun Mar 31 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379#issuecomment-478363612)

@BryanTrach-MSFT I think this is a location problem. If I compare the link I get and you get I only see that the end of the url is different because I use a german OS with Edge. So I think some magic in the backend happends and I get the url with the de-de at the end. Can we please investiagte a little bit more here. I think this link is broken for all people that don't use a en-us Browser profil.

---

@BryanTrach-MSFT commented on [Mon Apr 01 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379#issuecomment-478765573)

@paule96 The de-de page uses the exact same shortcut URL as the en-us page. When using a en-us browser I am properly redirected no matter if I am using the en-us page or the de-de page.

en-us URL: https://go.microsoft.com/fwlink/?LinkId=246619
de-de URL: https://go.microsoft.com/fwlink/?LinkId=246619

Sample from de-de page:
### <a name="web-server-logs"></a>Webserverprotokolle
Webserverprotokolle werden im [erweiterten W3C-Protokolldateiformat](https://msdn.microsoft.com/library/windows/desktop/aa814385.aspx)gespeichert. Die Informationen können in einem Texteditor gelesen oder mit einem Dienstprogramm wie [Log Parser](https://go.microsoft.com/fwlink/?LinkId=246619)analysiert werden.

@Sara-Nicolini Can you please take a look at this? The OP is claimng that when they click on the Log Parser link at the very bottom of the page it redirects them to the wrong page. I have been unable to reproduce the issue. OP believes it might be because they are using a german browser and OS setting. Should the doc be updated with the full URL rather than a shortcut URL?

Full URL with en-us removed: https://www.microsoft.com/download/details.aspx?displaylang=en&id=24659

---

@paule96 commented on [Wed Apr 03 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379#issuecomment-479535975)

Okay it is the shortcut url. If I use the long URL it works.
So the redirection is wrong in Germany. 🤷‍♀️

---

@Sara-Nicolini commented on [Fri Apr 12 2019](https://github.com/MicrosoftDocs/azure-docs/issues/26379#issuecomment-482727885)

@BryanTrach-MSFT, please help assign issue to @DavidPrio.
@SunnyDeng, FYI.

**Comment by cabrauck** [comment]
Hi, 

the link doesn`t work for me too. 
I am at https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#web-server-logs and the "here" is linked to https://go.microsoft.com/fwlink/?LinkId=246619 that doesnt work. I tried **aka.ms/LogParser**, works fine and redirect to https://www.microsoft.com/en-us/download/details.aspx?id=24659
**LinkOwner is petrmo** 

cheers Carsten

**Comment by CeciAc** [comment]
Hi team, 
Engineer team checked this issue and got the same results as @BryanTrach-MSFT above.
Assigning back to @ishasahni1 since this is out of our scope.

Kind regards
Microsoft DOCS International Team

**Comment by ishasahni1** [comment]
@CeciAc I tried on my end and I don't see the issue repro. I will ask Bodhi to help on this, to see if there is some fix needed on Docs platform.

@bodhigautam can you kindly help in looking into this issue.

**Comment by aldonetti** [comment]
I also just tried (from out of Corpnet) and I get redirected to this URL which is a 404 (as expected since it has a wrong "=it-it" appended at the end)
[https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=24659=it-it](https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=24659=it-it)  

but there is also an issue with https vs http
aka.ms/logparser redirects to -> aka.ms/logparser
http://www.microsoft.com/en-us/download/details.aspx?id=24659 (shown correctly)
but as soon as I hit refresh, the URL is changed into its secure version
httpS://www.microsoft.com/en-us/download/details.aspx?id=24659 and it fails (404)

**Comment by bodhigautam** [comment]
We are working to get this issue resolved with the help of engineerign team. cc @ishasahni1 @aldonetti @CeciAc

**Comment by CeciAc** [comment]
Hi @bodhigautam 
Is this still in process?

**Comment by ishasahni1** [comment]
@CeciAc this issue has been fixed now, so we no longer get 404.

**Comment by CeciAc** [comment]
Hi @paule96

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#web-server-logs
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by paule96** [comment]
A big thank you to the hole team :) you are amazing 🐱‍🏍
