### ISSUE TITLE
Guide is not up to date

### ISSUE THREAD

**Issue by Eiffelsturm** [MicrosoftDocs/azure-docs.de-de#286]
At least the guide for starting certificate order is not up to date. In the Azure Portal there are many new options which are missing in this article

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fa7e21c2-d024-dda5-a468-b140422b9fae
* Version Independent ID: 5475c8e6-1186-8ed1-2ad6-6eaa2cac871f
* Content: [Kaufen und Konfigurieren eines SSL-Zertifikats von Azure – Azure App Service](https://docs.microsoft.com/de-de/azure/app-service/web-sites-purchase-ssl-web-site#feedback)
* Content Source: [articles/app-service/web-sites-purchase-ssl-web-site.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/app-service/web-sites-purchase-ssl-web-site.md)
* Service: **app-service**
* GitHub Login: @cephalin
* Microsoft Alias: **apurvajo;cephalin**

**Comment by Eiffelsturm** [comment]
I'm sorry, I've confused that with something else.

**Comment by CeciAc** [comment]
Hello, @Eiffelsturm
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Eiffelsturm
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Eiffelsturm
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
