### ISSUE TITLE
SAML SSO without Application Proxy

### ISSUE THREAD

**Issue by mrmueller** [MicrosoftDocs/azure-docs.de-de#299]
Hi,

I don't understand why i would nedd Application Proxy to do SAML SSO with an on-prem application. I can do that today, the app and AAD do not need to communicatio to each other, I just need to establish the saml trust relationship. Just the browser needs access to SP and IDP.

I understand that Application Proxy can publish the app to the internet, but what value does it provide in the SAML context?

Could you clarify? Thanks

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 9f3d6933-1981-b6b5-b60a-2de762a0bef1
* Version Independent ID: af509d65-66e3-75f4-d3f4-7def020821a3
* Content: [SAML-SSO (einmaliges Anmelden) für lokale Anwendungen mit dem Azure Active Directory-Anwendungsproxy (Vorschauversion)](https://docs.microsoft.com/de-ch/azure/active-directory/manage-apps/application-proxy-configure-single-sign-on-on-premises-apps)
* Content Source: [articles/active-directory/manage-apps/application-proxy-configure-single-sign-on-on-premises-apps.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/manage-apps/application-proxy-configure-single-sign-on-on-premises-apps.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by CeciAc** [comment]
Hello, @mrmueller

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
