### ISSUE TITLE
GA of new vnet integration

### ISSUE THREAD

**Issue by gstolz** [MicrosoftDocs/azure-docs.de-de#316]
Hi, is there a schedule when the new vnet integration will generally be available? 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a7a98803-1438-b1b5-f543-7dd88bc4294e
* Version Independent ID: 37ff1d0f-ed8e-5e4d-1f4c-1b9f6cffb938
* Content: [Integrieren einer App in ein Azure Virtual Network – Azure App Service](https://docs.microsoft.com/de-de/azure/app-service/web-sites-integrate-with-vnet#new-vnet-integration)
* Content Source: [articles/app-service/web-sites-integrate-with-vnet.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/app-service/web-sites-integrate-with-vnet.md)
* Service: **app-service**
* GitHub Login: @ccompy
* Microsoft Alias: **ccompy**

**Comment by CeciAc** [comment]
Hello, @gstolz

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
