### ISSUE TITLE
Azure IoT Edge pipeline plugin - Project structure

### ISSUE THREAD

**Issue by burgerTo** [MicrosoftDocs/azure-docs.de-de#341]
I want to build a azure pipeline which builds and deploys an iot edge solution. So, I followed this tutorial https://docs.microsoft.com/de-de/azure/iot-edge/how-to-ci-cd, which fits perfect for my usecase. 

I created my edge-solution with the visual studio plugin, following this tutorial: https://docs.microsoft.com/de-de/azure/iot-edge/how-to-visual-studio-develop-module 
According to the azure Iot edge CI documentation, this is a supported project structure for the pipeline plugin. But it's different to the project structure, which is created by visual studio code. 

Running the pipeline, i run into errors which indicates that a visual studio code structure is expected. 

```
##[section]Starting: Azure IoT Edge - Build and Push modules
==============================================================================
Task         : Azure IoT Edge
Description  : Azure IoT Edge
Version      : 1.1.2
Author       : Microsoft
Help         : 
==============================================================================
/home/vsts/work/1/s /home/vsts/work/1/s
Building and pushing image...
##[error]Error: ENOENT: no such file or directory, scandir '/home/vsts/work/1/s/modules'
##[section]Finishing: Azure IoT Edge - Build and Push modules
```

Will the azure iot edge pipeline plugin only support the vs-code structure? 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a4d641df-10ad-411d-81d8-96ec6aa4b4fe
* Version Independent ID: ce520c59-364b-7bbf-6200-76feaee6eacf
* Content: [Continuous Integration und Continuous Deployment – Azure IoT Edge](https://docs.microsoft.com/de-de/azure/iot-edge/how-to-ci-cd)
* Content Source: [articles/iot-edge/how-to-ci-cd.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-edge/how-to-ci-cd.md)
* Service: **iot-edge**
* GitHub Login: @shizn
* Microsoft Alias: **xshi**

**Comment by CeciAc** [comment]
Hello, @burgerTo 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by shizn** [comment]
@burgerTo  Thanks for your valuable feedback. VS structure is not supported at this moment. We will enable this by the end of June. If you would like to try Azure DevOps plugin, one easy way at this moment is to switch to VS Code structure. Sorry for the inconvenience.

**Comment by burgerTo** [comment]
@shizn Thanks for clarification. I will try it with the visual code structure. 

@CeciAc In this case, i think this issue is related to the docs. The documentation describes: 

> An IoT Edge solution committed and pushed to your repository. If you want to create a new sample solution for testing this article, follow the steps in Develop and debug modules in Visual Studio Code or Develop and debug C# modules in Visual Studio.

The prerequesit "Develop and debug C# modules in Visual Studio" (+ linked howto) is currently not supported for this plugin.
