### ISSUE TITLE
validation failed due to missing parameter

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/azure-docs.de-de#360]
On the final validation page I receive the following error:
"Validation failed, see errors below.
InvalidTemplateDeployment template validation failed: 'The template parameter 'baseUrl' is not found. Please see https://aka.ms/arm-template/#parameters for usage details.'."

I seems that the GUI workflow is missing to ask for the value of a required attribute?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 970202b7-165f-18df-e928-c47c45a18755
* Version Independent ID: d5393b62-4211-72f5-fc7a-363f68f6d8a2
* Content: [Erstellen eines Hostpools für die Vorschauversion von Windows Virtual Desktop mit Azure Marketplace – Azure](https://docs.microsoft.com/de-de/azure/virtual-desktop/create-host-pools-azure-marketplace)
* Content Source: [articles/virtual-desktop/create-host-pools-azure-marketplace.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/virtual-desktop/create-host-pools-azure-marketplace.md)
* Service: **virtual-desktop**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by CeciAc** [comment]
Hello, @SRE93

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
