### ISSUE TITLE
German translation issue: "Endusers"

### ISSUE THREAD

**Issue by finius** [MicrosoftDocs/azure-docs.de-de#370]
German description says, that user can't connect with a WVD client to their environment after they've been assigned to a RemoteApp group.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b7a8e997-f5c8-eaa8-b713-068650dd6b22
* Version Independent ID: ef57850d-1fc4-bc6a-827c-2934c31f50c9
* Content: [Windows Virtual Desktop-Umgebung (Vorschauversion) – Azure](https://docs.microsoft.com/de-de/azure/virtual-desktop/environment-setup#feedback)
* Content Source: [articles/virtual-desktop/environment-setup.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/virtual-desktop/environment-setup.md)
* Service: **virtual-desktop**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by ishasahni1** [comment]
@CeciAc can you kindly look into this issue as it is open from such a long time.

**Comment by CeciAc** [comment]
Hello, @finius

Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@ishasahni1 it looks like this issue was misplaced due a technical issue and wasn't picked by our tool, 
I already reported it and we are working on it now

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @finius 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/azure/virtual-desktop/environment-setup#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
