### ISSUE TITLE
Gut erklärt, aber Java Error

### ISSUE THREAD

**Issue by Endinger75** [MicrosoftDocs/azure-docs.de-de#430]
Das Tut ist zwar gut erklärt, sodass ein App-Leihe wie ich auch damit umgehen kann, nur bekomme ich beim speichern bzw. "in die cloud senden" eines zuerst gelben AR-Objekts mit der fertigen Java-App auf meinem Galaxy S8 folgenden Fehlercode (und die AR-Kugel wird rot), welchen ich auch nach einer Internetrecherche nicht ergründen kann: 
java.util.concurrent.CompletionExeption: java.lang.RuntimeExeption: java.util.concurrent.ExecutionExeption: java.lang.IllegalStateExeption: std::exeption.Request CV:- Response CV:.
Gibt es hier ein Forum oder Ähnliches welches weiterhelfen könnte oder muss ich mich in Java einarbeiten? 
Merci schon mal.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e263a867-f6c6-0ac2-baad-57059396e839
* Version Independent ID: 1fa20d5b-660c-026c-7edc-4e6322d19812
* Content: [Schnellstart: Erstellen einer Android-App mit Azure Spatial Anchors](https://docs.microsoft.com/de-de/azure/spatial-anchors/quickstarts/get-started-android?tabs=openproject-java#feedback)
* Content Source: [articles/spatial-anchors/quickstarts/get-started-android.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/spatial-anchors/quickstarts/get-started-android.md)
* Service: **azure-spatial-anchors**
* GitHub Login: @craigktreasure
* Microsoft Alias: **crtreasu**

**Comment by CeciAc** [comment]
Hallo, @Endinger75 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
