### ISSUE TITLE
Markup not rendering picture references on titles

### ISSUE THREAD

**Issue by totosan** [MicrosoftDocs/azure-docs.de-de#442]
Hey guys,

there are picture references, that are not rendered.
 
e.g.: 
"...
'![Moby as container runtime](./media/support/only-moby-for-production.png)

Operating systems
.."
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bf820bbb-9fc6-2037-6d72-c63192763ed6
* Version Independent ID: b0c7e11b-3741-15f6-58e7-8529d492af47
* Content: [Unterstützte Betriebssystem, Containerengines – Azure IoT Edge](https://docs.microsoft.com/de-de/azure/iot-edge/support)
* Content Source: [articles/iot-edge/support.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-edge/support.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by CeciAc** [comment]
Hello, @totosan
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @totosan
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by totosan** [comment]
of course. Sorry for the delay. If you'are Opening up the page you should see this here 
![image](https://user-images.githubusercontent.com/7992807/60682997-d60cf580-9e95-11e9-8a20-10a7ae12ced6.png)
I don't think, that this is how it should be. (Language is german, but shouldn't do any matter). Hope this helps.

regards,
Thomas

**Comment by CeciAc** [comment]
Hi @totosan
Thanks for your clarification.
I tried it on my end and cannot repro the error
![imagen](https://user-images.githubusercontent.com/26746247/60685246-62102480-9e78-11e9-84b8-aab79ad35d8a.png)

Can you please try these two things:
1) Check the en-US site to see if you are having the same issue: https://docs.microsoft.com/en-us/azure/iot-edge/support

2) Try with another browser.

@ishasahni1 @DavidPrio

**Comment by totosan** [comment]
Hi @CeciAc ,

calling site from Chrome with en-US works. ...german version too. Now also it's working on Edge and Firefox. Thx! May be this was an issue with edge or a temporary break; but never mind I think this issue can be closed.
