### ISSUE TITLE
Links in section next steps are interchanged

### ISSUE THREAD

**Issue by Softgrider** [MicrosoftDocs/azure-docs.de-de#443]
"Verbund" points to "verwaltet"
"verwaltet" points to "Verbund"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 72cdc251-618a-e84e-f40d-960b0ac69f99
* Version Independent ID: 8cbaba3c-e883-2c71-28fb-f88db3fcaf7d
* Content: [Planen der Implementierung einer Azure Active Directory-Hybrideinbindung in Azure Active Directory (Azure AD)](https://docs.microsoft.com/de-de/azure/active-directory/devices/hybrid-azuread-join-plan#feedback)
* Content Source: [articles/active-directory/devices/hybrid-azuread-join-plan.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/devices/hybrid-azuread-join-plan.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by CeciAc** [comment]
Hello, @Softgrider
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by Softgrider** [comment]
There are two links in the section "Nächste Schritte" (Next steps)
"Konfigurieren von Azure Active Directory-Hybrideinbindung für eine verwaltete Umgebung"
points to "https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/devices/hybrid-azuread-join-federated-domains.md"
and
"Konfigurieren von Azure Active Directory-Hybrideinbindung für eine Verbundumgebung" points to "https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-"directory/devices/hybrid-azuread-join-managed-domains.md"
The links are interchanged. 

German: Verbund -> English: federated
verwaltet -> managed

**Comment by CeciAc** [comment]
Hello, @Softgrider 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team
