### ISSUE TITLE
az vm encryption enable cross subscriptions (VM/KeyVault)

### ISSUE THREAD

**Issue by ithahn** [MicrosoftDocs/azure-docs.de-de#445]
Hi,

as stated in the document we have tried to following Code:
az vm encryption enable --resource-group "MyVirtualMachineResourceGroup" --name "MySecureVM" --disk-encryption-keyvault  "MySecureVault" --key-encryption-key "MyKEK_URI" --key-encryption-keyvault "MySecureVaultContainingTheKEK" --volume-type "All"

When we use this in the Cloud Shell we get the following error:
Resource Group "MySecureVault" Cloud not be found.

I Need to say that the VM and the KeyVault are in different subscriptions.
The KeyVault got all needed Access policies enabled. So this can't be the issue.

Can someone please support on this issue?

Thanks,
Klaus

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d7c63605-95f5-0953-3cf6-1e9c50532c1d
* Version Independent ID: 8731daa8-2c15-78f7-adac-151401c13b6c
* Content: [Aktivieren von Azure Disk Encryption für virtuelle Windows-IaaS-Computer](https://docs.microsoft.com/de-de/azure/security/azure-security-disk-encryption-windows#feedback)
* Content Source: [articles/security/azure-security-disk-encryption-windows.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/security/azure-security-disk-encryption-windows.md)
* Service: **security**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by CeciAc** [comment]
Hello, @ithahn

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
