### ISSUE TITLE
Request Count

### ISSUE THREAD

**Issue by matlion** [MicrosoftDocs/azure-docs.de-de#460]
&gt; Azure CDN has a limit of 50 concurrent purge requests at any given time at the profile level.

How do you determine the request limit?
We encountered errors when concurrently calling about 25 requests with more than 50 paths in summary?
So do azure count each single path as a purge request, so that we have to limit the number of paths called concurrently?

We use Pricing Tier: Standard Verizon

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6126b381-b857-a1e4-5476-d8d37e76f3b6
* Version Independent ID: 39d12a94-9bb4-54e1-8105-47b6777c1d23
* Content: [Löschen eines Azure CDN-Endpunkts](https://docs.microsoft.com/de-de/azure/cdn/cdn-purge-endpoint#feedback)
* Content Source: [articles/cdn/cdn-purge-endpoint.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cdn/cdn-purge-endpoint.md)
* Service: **azure-cdn**
* GitHub Login: @mdgattuso
* Microsoft Alias: **magattus**

**Comment by matlion** [comment]
Additional Information: 
Pricing Tier: Standard Verizon

**Comment by lichasu** [comment]
Hello, @matlion ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
