### ISSUE TITLE
Title of the document does not match to the content

### ISSUE THREAD

**Issue by nocheinlarry** [MicrosoftDocs/azure-docs.de-de#464]
Headline German is: Verwenden der Advanced Data Security einer Azure SQL-Datenbank mit virtuellen Netzwerken und nahezu 100iger % Kompatibilität

Headline from Link expected:
Überblick über Azure SQL - Verwaltete Instanz

Could you please verfiy if the headline can be changed?

Best regards, Thomas 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 28ca1f7f-5a34-0f23-10ce-3ff24c76db97
* Version Independent ID: 5c4a22c4-78fc-911d-9fa0-8dfab1653b6e
* Content: [Azure SQL-Datenbank – Advanced Data Security](https://docs.microsoft.com/de-de/azure/sql-database/sql-database-managed-instance#feedback)
* Content Source: [articles/sql-database/sql-database-managed-instance.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/sql-database/sql-database-managed-instance.md)
* Service: **sql-database**
* Sub-service: **managed-instance**
* GitHub Login: @bonova
* Microsoft Alias: **bonova**

**Comment by lichasu** [comment]
Hello, @nocheinlarry   

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @nocheinlarry  

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/azure/sql-database/sql-database-managed-instance

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
