### ISSUE TITLE
Installationsanweisungen unter Debian 9

### ISSUE THREAD

**Issue by kitingChris** [MicrosoftDocs/azure-docs.de-de#485]
```
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/debian/$(lsb_release -rs)/prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
```
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b2646ad4-34b7-fc5e-dcc9-d53a061df394
* Version Independent ID: bbff4fda-24e4-2b62-24b9-94cda5f53bed
* Content: [Arbeiten mit Azure Functions Core Tools](https://docs.microsoft.com/de-de/azure/azure-functions/functions-run-local#feedback)
* Content Source: [articles/azure-functions/functions-run-local.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-functions/functions-run-local.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by srvbpigh** [comment]
Hello, @kitingChris
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @kitingChris 
Wir freuen uns über Ihren Kommentar und bemühen uns, Ihre Erfahrungen mit docs.microsoft.com zu verbessern. Wir benötigen jedoch weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern?
Mit freundlichen Grüßen
Microsoft DOCS International Team

**Comment by kitingChris** [comment]
Hi, hab dazu schon einen PR gestellt https://github.com/MicrosoftDocs/azure-docs.de-de/pull/486

**Comment by CeciAc** [comment]
Hallo, @kitingChris

vielen Dank für Ihren Beitrag. unser Team hat sich Ihr Feedback angesehen. Es sieht so aus, als sei dieses Problem bereits gemeldet worden. 

Bitte sehen Sie sich Problem https://github.com/MicrosoftDocs/azure-docs.de-de/pull/486 an. Wir schließen dieses Problem, da es doppelt vorkommt. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by kitingChris** [comment]
@CeciAc hey wie lange soll es noch dauern bis der PR bearbeitet wird? Alle 3 Tage mit einer automatisierten Nachricht zu nerven ist wenig hilfreich und führt nur dazu dass ich das zukünftig sein lasse und ggf. den PR demnächst entnervt zurückziehe.
