### ISSUE TITLE
avro in Azure Storage Explorer not working

### ISSUE THREAD

**Issue by dbe-it** [MicrosoftDocs/azure-docs.de-de#510]
"You can view these files in any tool such as Azure Storage Explorer." is absolutely not true.  You can list them but opening a avro file leads to a "unsupported filename" error. Even on current version of azure storage explorer (1.9.0). And if you choose "Encode filename and download as [..]" the default program for all avro-files on the OS will be opened.

That is really bad! Viewing the "own" file-format doesn't work. For what do I need the explorer? 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 71093e2a-bbff-3a79-5f16-289a3a5f6cd7
* Version Independent ID: e4e9873d-0ae7-25a4-16d1-5ecac6e84b91
* Content: [Erfassen von Streamingereignissen: Azure Event Hubs](https://docs.microsoft.com/de-de/azure/event-hubs/event-hubs-capture-overview#feedback)
* Content Source: [articles/event-hubs/event-hubs-capture-overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/event-hubs/event-hubs-capture-overview.md)
* Service: **event-hubs**
* GitHub Login: @ShubhaVijayasarathy
* Microsoft Alias: **shvija**

**Comment by srvbpigh** [comment]
Hello, @dbe-it
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @dbe-it

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
