### ISSUE TITLE
Access token lifetime max value "24:00:00" invalid.

### ISSUE THREAD

**Issue by florianeidner** [MicrosoftDocs/azure-docs.de-de#511]
Access token lifetime cannot be set to "24:00:00" by New-AzureADPolicy cmdlet. The powershell cmdlet returns an error if i want to set it to 24h. The max working value seems to be 23:59:59.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 02ff3d62-dc0e-ad0c-f5ae-418337cf31e4
* Version Independent ID: d50952b5-6b98-c40d-d3a3-f9cbec58dd28
* Content: [Konfigurierbare Tokengültigkeitsdauern in Azure Active Directory](https://docs.microsoft.com/de-de/azure/active-directory/develop/active-directory-configurable-token-lifetimes#get-azureadpolicyappliedobject)
* Content Source: [articles/active-directory/develop/active-directory-configurable-token-lifetimes.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/develop/active-directory-configurable-token-lifetimes.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @florianeidner
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by florianeidner** [comment]
The max acvess token lifetime has to be provided in the format: 1.00:00:00
