### ISSUE TITLE
Powershell doesn't show property "Available Memory"

### ISSUE THREAD

**Issue by tspannagel** [MicrosoftDocs/azure-docs.de-de#512]
The powershell command Get-AzDataFactoryV2IntegrationRuntime doesn't show the property "Available Memory" as listed in https://docs.microsoft.com/de-de/azure/data-factory/monitor-integration-runtime#self-hosted-integration-runtime

Available Properties:
State                     
Version                   
CreateTime                
AutoUpdate                
ScheduledUpdateDate       
UpdateDelayOffset         
LocalTimeZoneOffset       
InternalChannelEncryption 
Capabilities              
	serviceBusConnected        
	httpsPortEnabled           
	credentialInSync           
	connectedToResourceManager 
	nodeEnabled                
ServiceUrlS                                      
Nodes     
	NodeName             
	MachineName          
	HostServiceUri       
	Status               
	Capabilities        
		serviceBusConnected       
		httpsPortEnabled          
		credentialInSync          
		connectedToResourceManager
		nodeEnabled               
		dotNetVersion             
	VersionStatus        
	Version              
	RegisterTime         
	LastConnectTime      
	ExpiryTime           
	LastStartTime        
	LastStopTime         
	LastUpdateResult     
	LastStartUpdateTime  
	LastEndUpdateTime    
	IsActiveDispatcher   
	ConcurrentJobsLimit  
	MaxConcurrentJobs    
Links                     
Name                      
Type                      
ResourceGroupName         
DataFactoryName           
Description               
Id                       

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7f114f7a-7512-a610-b4ba-271bb946de0a
* Version Independent ID: 9d7555ed-3884-da9b-7695-36b760881a82
* Content: [Überwachen der Integrationslaufzeit in Azure Data Factory](https://docs.microsoft.com/de-de/azure/data-factory/monitor-integration-runtime)
* Content Source: [articles/data-factory/monitor-integration-runtime.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/data-factory/monitor-integration-runtime.md)
* Service: **data-factory**
* GitHub Login: @gauravmalhot
* Microsoft Alias: **gamal**

**Comment by srvbpigh** [comment]
Hello, @tspannagel
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #37365](https://github.com/MicrosoftDocs/azure-docs/issues/37365) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @tspannagel

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/37365.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
