### ISSUE TITLE
Association of backend pool to AKS Node

### ISSUE THREAD

**Issue by fajanssen** [MicrosoftDocs/azure-docs.de-de#521]
Hey Azure Docs team,

I don't get how the Application Gateway resource is now connected to the AKS-Nodes. There is an empty backend pool defined but i do not see any association of AKS-Nodes to the pool. Where and how is this done in this Tutorial?

Greetings Fabian

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 20f12c89-40e2-076e-6135-64773551e673
* Version Independent ID: c2d6ac4a-fad9-dbc1-d125-b267bcd2a566
* Content: [Erstellen eines Kubernetes-Clusters mit Application Gateway als Eingangscontroller mit Azure Kubernetes Service (AKS)](https://docs.microsoft.com/de-de/azure/terraform/terraform-create-k8s-cluster-with-aks-applicationgateway-ingress#prerequisites)
* Content Source: [articles/terraform/terraform-create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/terraform/terraform-create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **azure**
* GitHub Login: @TomArcher
* Microsoft Alias: **tarcher**

**Comment by CeciAc** [comment]
Hello, @fajanssen

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
