### ISSUE TITLE
Azure Credits isn't shown in the menu

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/azure-docs.de-de#523]
I suspect that the submenu point shown in the 2nd and 3rd screenshot is outdated/not valid anymore. This assumption is supported by the fact that the first screenshot shows 'Cost Management + Billing' as in preview although it isn't in preview anymore.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a358d6ed-dc54-d6b8-4550-4333b5c77c5c
* Version Independent ID: 49a4636f-d4e1-4793-8ce9-7f7ea9056582
* Content: [Nachverfolgen des Azure-Gutschriftensaldos für eine Microsoft-Kundenvereinbarung](https://docs.microsoft.com/de-de/azure/billing/billing-mca-check-azure-credits-balance)
* Content Source: [articles/billing/billing-mca-check-azure-credits-balance.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/billing/billing-mca-check-azure-credits-balance.md)
* Service: **billing**
* GitHub Login: @bandersmsft
* Microsoft Alias: **banders**

**Comment by srvbpigh** [comment]
Hello, @GiantCrocodile
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by bandersmsft** [comment]
@GiantCrocodile Thanks for the feedback. I'm looking into this issue. If new screenshots are needed, I'll update them.
#in-process

**Comment by CeciAc** [comment]
@ishasahni1 I assigned this issue to you so you can check it
Loc team reports these arts are blocked.

**Comment by ishasahni1** [comment]
@ceciac there is no action item on localization side, as we don't localize the art files. Looks like this is an action item for content team to look into and update with new images if needed.

@bandermsft is already looking into it.

**Comment by ishasahni1** [comment]
@bandersmsft can you kindly help us with looking into this issue as it is still open.

**Comment by bandersmsft** [comment]
@ishasahni1 @GiantCrocodile
- I updated the first screenshot showing the current search behavior (to remove the preview mention) with https://github.com/MicrosoftDocs/azure-docs-pr/pull/92440 
- The other screenshots on the page are still current/valid. 
- In order to view credits (as explained in the article): You must have an owner, contributor, reader, or invoice manager role on the billing profile or owner, contributor, or reader role on the billing account to view Azure credit balance for a billing profile. 
#pelase-close

**Comment by GiantCrocodile** [comment]
@bandersmsft So am I right that point 3 (the permission thing) isn't given if you are simply the admin of the Azure tenant/account? I suspected this is visible as an admin with all permissions.

**Comment by bandersmsft** [comment]
@GiantCrocodile @amberbhargava Amber can elaborate.

**Comment by amberbhargava** [comment]
@GiantCrocodile - This article applies only to customers with access to a Microsoft Customer Agreement billing account. If you are an admin of a tenant, which has a user who has a Microsoft Customer Agreement billing account, you'll get implicit access to the account. If you're not seeing Azure credits in the left nav, that means you don't have access to a Microsoft Customer Agreement billing account.

**Comment by GiantCrocodile** [comment]
I will get back to you to see if I can verify what you have said within the next one or two days. I'm not sure if this is the reason why we face this. Please keep this issue open until then.

Thank you for your answer @amberbhargava!

**Comment by GiantCrocodile** [comment]
I can approve what @amberbhargava said and thus I will close this issue. Thank you guys!
