### ISSUE TITLE
There's no sound

### ISSUE THREAD

**Issue by elinside** [MicrosoftDocs/azure-docs.de-de#527]
Hello, I worked through this tutorial and i get the last picture exactly the same, but there is no sound coming out of the speakers. I have only one speaker, and my sound is working from other apps. What did i miss?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fb91ed32-1d9f-246d-1553-f3e9c959e537
* Version Independent ID: 1114f1a1-c5c6-7722-7f76-b1aeedaea7e4
* Content: [Schnellstart: Synthetisieren von Sprache, C# (.NET Core) – Speech-Dienst - Azure Cognitive Services](https://docs.microsoft.com/de-de/azure/cognitive-services/speech-service/quickstart-text-to-speech-dotnetcore#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/quickstart-text-to-speech-dotnetcore.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cognitive-services/Speech-Service/quickstart-text-to-speech-dotnetcore.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @yinhew
* Microsoft Alias: **yinhew**

**Comment by srvbpigh** [comment]
Hello, @elinside
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @elinside

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
