### ISSUE TITLE
"Ihr Beitrag wird derzeit noch geprüft. Wir informieren Sie in Kürze über die Entscheidung." 

### ISSUE THREAD

**Issue by kitingChris** [MicrosoftDocs/azure-docs.de-de#533]
Nachdem euer Bot mich alle 3 Tage damit nervt dass der PR #486 noch in Bearbeitung ist sich aber seit mehr als einem Monat offensichtlich keiner dafür interessiert schließe ich den PR.
Werde dann wohl in Zukunft auch keine Verbesserungsvorschläge mehr machen.
Schaltet doch zumindest den Bot nach der zweiten Benachrichtigung ab.
Alle 3 Tage zu sagen der PR sei noch in Bearbeitung ist sinnlos und nervtötend!

**Comment by srvbpigh** [comment]
Hello, @kitingChris
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
