### ISSUE TITLE
Missing documentation of maximum event size for "Basic" tier event hubs

### ISSUE THREAD

**Issue by PhilippJust** [MicrosoftDocs/azure-docs.de-de#534]
When sending an event with a size of 360kiByte to an event hub that uses the basic tier, I kept on receiving following error message:

```xml
&lt;Error&gt;
&lt;Code&gt;413&lt;/Code&gt;
&lt;Detail&gt;The maximum message size quota for outgoing messages (327680) has been exceeded. TrackingId:6da40525-8836-4976-b1e3-75a574176faa_G18, SystemTracker:xxxxxxx:EventHub:xxxxxxxxxxxx, Timestamp:2019-09-09T14:26:31&lt;/Detail&gt;
&lt;/Error&gt;
```

When I upscaled the event hub namespace to standard, this error disappeared.
For me this seems like basic tier event hubs only allow 320 kiByte event size. Please verify that and add it to the docs.

Thanks a lot!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b6d43eb3-6a80-b8c4-8536-f4f8b79aa453
* Version Independent ID: 3e8dec68-44ac-aca8-5b07-470050878ae5
* Content: [Kontingente und Grenzwerte – Azure Event Hubs](https://docs.microsoft.com/de-de/azure/event-hubs/event-hubs-quotas#feedback)
* Content Source: [articles/event-hubs/event-hubs-quotas.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/event-hubs/event-hubs-quotas.md)
* Service: **event-hubs**
* GitHub Login: @ShubhaVijayasarathy
* Microsoft Alias: **shvija**

**Comment by srvbpigh** [comment]
Hello, @PhilippJust
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/38643

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
