### ISSUE TITLE
Passing real content to function does not work

### ISSUE THREAD

**Issue by cepxy** [MicrosoftDocs/azure-docs.de-de#536]
We are using a java function with queue trigger, input is a complex json.
Entering { "input": "test" } does reach the function and it gets executed but this is not the data we expect in our function as trigger input.
If I set the body to the json-data that we expect it is not working anymore. The functions logs: "Unable to convert trigger to BrokeredMessage."
If I surround my content with {"input":{...} I get a 400.
How does it work to pass the real data into the function?
Regards

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f538a557-7e88-e077-6a6f-6fb14d89dbf6
* Version Independent ID: 84a1693b-2795-c865-35df-3ad3b9b61e2c
* Content: [Manuelles Ausführen einer Azure-Funktion ohne HTTP-Trigger](https://docs.microsoft.com/de-de/azure/azure-functions/functions-manually-run-non-http#feedback)
* Content Source: [articles/azure-functions/functions-manually-run-non-http.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-functions/functions-manually-run-non-http.md)
* Service: **azure-functions**
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by srvbpigh** [comment]
Hello, @cepxy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @cepxy

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
