### ISSUE TITLE
No documentation for ACI properties.readinessProbe

### ISSUE THREAD

**Issue by Herr-Sepp** [MicrosoftDocs/azure-docs.de-de#545]
The ACI documentation completely lacks the API item "properties.readinessProbe".

Since the API documentation (https://docs.microsoft.com/de-de/rest/api/container-instances/containergroups/createorupdate#containerprobe )does not distinguish between liveProbe and readinessProbe, and since no example with readiness Prob is shown, a "Configure readiness probes" Doc-page would be desirable.

What does ACI do if the readinessProbe fails? Also restart the container like the liveProbe?
Can you use the readinessProbe to wait for other containers in the group to fully boot before starting the next one?

What is a "exits successfully" for HttpGet-Probe? All 2XX or only 200?

An example with httpGet, failureThreshold and successThreshold would bring more clarity also for the liveProbe where these parameters are not explained.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 64b5c5a2-21f2-e3ac-bddf-27ecf3994331
* Version Independent ID: 34084e0d-f3d0-aa56-d065-b087027ab97c
* Content: [Konfigurieren von Livetests in Azure Container Instances](https://docs.microsoft.com/de-de/azure/container-instances/container-instances-liveness-probe)
* Content Source: [articles/container-instances/container-instances-liveness-probe.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/container-instances/container-instances-liveness-probe.md)
* Service: **container-instances**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by srvbpigh** [comment]
Hello, @Herr-Sepp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #38952](https://github.com/MicrosoftDocs/azure-docs/issues/38952) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Herr-Sepp

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/38952

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
