### ISSUE TITLE
not existing Link

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/azure-docs.de-de#551]
There is a link for a code example with 
Python	IoTHubTransportProvider.MQTT
but the link does is not exist
https://github.com/Azure/azure-iot-sdk-python/tree/master/device/samples

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bcf2a86a-1de0-2786-db87-58279ceffb22
* Version Independent ID: 7e43624f-a87d-1c4d-94e6-e38c1d42686f
* Content: [Grundlegendes zur Azure IoT Hub MQTT-Unterstützung](https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-mqtt-support)
* Content Source: [articles/iot-hub/iot-hub-mqtt-support.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-hub/iot-hub-mqtt-support.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robinsh**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by robinsh** [comment]
@aisbergde I don't know where you got that link -- are you opening it from the Docs website, or from a copy of the markdown article? In the doc itself, the link is 
https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples.
Looks like /device/ got updated to /azure-iot-device/ at some point, making it a working link. I'm not sure how long it takes to internationalize the articles, but maybe they haven't updated the German version yet? Try it again now and see if it's been corrected.

**Comment by aisbergde** [comment]
The link is wrong in the German article. It is also wrong when I switch from German to English.
The issue is: even if I switch from German to English I don't get the original English article but I am still in the de-de section. It looks like a general issue with translated articles not showing the original even if the user wants to read the original article.

**Comment by CeciAc** [comment]
Hello, @aisbergde

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-mqtt-support

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
