### ISSUE TITLE
OperationNotAvailableInCurrentTier when using AddModule in BasicTier

### ISSUE THREAD

**Issue by MariuszKogut** [MicrosoftDocs/azure-docs.de-de#559]
I'm wonder why Microsoft.Azure.Devices.RegistryManager.AddModuleAsync is throwing OperationNotAvailableInCurrentTier Exception when using BasicTier. As I understood from  https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-scaling#iot-hub-rest-apis this should also be supported for BasicTiers, right?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 45b76f3e-0318-070e-ff9f-0598ed6379b1
* Version Independent ID: 52d8706b-30a2-93db-020c-1dc7098730f9
* Content: [Skalieren von Azure IoT Hub](https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-scaling#iot-hub-rest-apis)
* Content Source: [articles/iot-hub/iot-hub-scaling.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-hub/iot-hub-scaling.md)
* Service: **iot-hub**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by srvbpigh** [comment]
Hello, @MariuszKogut
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MariuszKogut

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by MariuszKogut** [comment]
@CeciAc 

My question to the documentation is: 
https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-scaling#iot-hub-rest-apis 

![image](https://user-images.githubusercontent.com/9637281/65571786-2f049b00-df66-11e9-8f47-e2195ffdeb92.png)

Your documentation says "Create or update module" is available in Basic tier. But it isn't.
I even can not create a module using Azure Portal. I guess your documentation is wrong or outdated. For a developer, it crucial to get valid documentation. So this is question is related to your documentation, right?

Clues:
Using Microsoft's official HttpApi Wrapper throws OperationNotAvailableInCurrentTier
```
{"Message":"ErrorCode:OperationNotAvailableInCurrentTier;This capability is not available for Basic Tier IoT Hub. Please visit https://aka.ms/StandardIoTHubUpgrade to learn about Standard Tier."
```

Azure Portal screenshot:
![image](https://user-images.githubusercontent.com/9637281/65571579-7b9ba680-df65-11e9-9db7-e87771f66736.png)
