### ISSUE TITLE
German translation values for "Stream" / "Datenstrom"

### ISSUE THREAD

**Issue by IlmMicha** [MicrosoftDocs/azure-docs.de-de#56]
Hello,
I think the nouns in table column "Stream"/"Datenstrom" should not be translated to german as they correspond with the PowerShell nouns in Write-Output, Write-Verbose, etc.

Regards,
Michael

**Comment by SunnyDeng** [comment]
@IlmMicha Michael, can you please point the article URL?

**Comment by SunnyDeng** [comment]
@IlmMicha ping the contributor again.

**Comment by SunnyDeng** [comment]
no contributor feedback, closed. 
@IlmMicha please feel free to reopen this ISSUE with the file URL.
