### ISSUE TITLE
the specific user-claims from the german site are still needed

### ISSUE THREAD

**Issue by doagl** [MicrosoftDocs/azure-docs.de-de#560]
Under Point 7 you've to add user specific claims:
RoleSessionName -&gt;	user.userprincipalname -&gt; https://aws.amazon.com/SAML/Attributes
Role -&gt; user.assignedroles -&gt; https://aws.amazon.com/SAML/Attributes
SessionDuration -&gt; „Geben Sie einen Wert zwischen 900 Sekunden (15 Minuten) und 43.200 Sekunden (12 Stunden) an“ -&gt; https://aws.amazon.com/SAML/Attributes

Those claims are missing in the en-us site.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8fa5814d-91e2-2f75-77e7-62a8597f340c
* Version Independent ID: 458e93d7-a180-4c2f-5077-9b9d124d726a
* Content: [Tutorial: Azure Active Directory-Integration mit Amazon Web Services (AWS)](https://docs.microsoft.com/de-de/azure/active-directory/saas-apps/amazon-web-service-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/amazon-web-service-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/saas-apps/amazon-web-service-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by srvbpigh** [comment]
Hello, @doagl
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by jeevansd** [comment]
@doagl Now these claims are automatically added once you add the application from the gallery. but for reference we will update the article to make sure that customer review them.

@v-viinde and @v-nagta Can you please make sure that you add these claims so that customer can verify it?

**Comment by CeciAc** [comment]
Hi @jeevansd 
I see the en-us page was recently update. The issue may be solve after next translation round.
Please, confirm if this solves the issue.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @doagl

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/azure/active-directory/saas-apps/amazon-web-service-tutorial#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
