### ISSUE TITLE
saved my day

### ISSUE THREAD

**Issue by tomtoepel** [MicrosoftDocs/azure-docs.de-de#571]
"HttpListener can listen on multiple addresses on the same port as long as the URL prefix is unique."
It's Important to know, when you create http listener for named or ranged partitions. The url prefix for http/https endpoints must be different for each partition. Now it works.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 553c01c6-2e91-cf8e-d658-9669f4c91fd4
* Version Independent ID: 05e7540a-969b-1f45-2193-4a2d721a32b6
* Content: [Partitionieren von Service Fabric-Diensten](https://docs.microsoft.com/de-de/azure/service-fabric/service-fabric-concepts-partitioning#feedback)
* Content Source: [articles/service-fabric/service-fabric-concepts-partitioning.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/service-fabric/service-fabric-concepts-partitioning.md)
* Service: **service-fabric**
* GitHub Login: @athinanthny
* Microsoft Alias: **atsenthi**

**Comment by srvbpigh** [comment]
Hello, @tomtoepel
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #39968](https://github.com/MicrosoftDocs/azure-docs/issues/39968) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @tomtoepel 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/39968.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
