### ISSUE TITLE
Header sample does not work

### ISSUE THREAD

**Issue by MarkusMeyer13** [MicrosoftDocs/azure-docs.de-de#575]
The sample code does not work:

```
@{
  string value;
  if (context.Request.Headers.TryGetValue("Authorization", out value))
  {
    return Encoding.UTF8.GetString(Convert.FromBase64String(value));
  }
  else
  {
    return null;
  }
}
```
Following exception will be displayed:

```
One or more fields contain incorrect values:
Fehler im Element 'set-variable' in Zeile 16, Spalte 2: Argument 2: cannot convert from 'out string' to 'out string[]'
```

![image](https://user-images.githubusercontent.com/8818198/66393438-d1933400-e9d2-11e9-9d0a-45a110462594.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2a90be78-63d0-8ee0-d1d6-a9280e2ba892
* Version Independent ID: 500c452d-372b-92a9-dfca-b2586669a9bf
* Content: [Richtlinienausdrücke in Azure API Management](https://docs.microsoft.com/de-de/azure/api-management/api-management-policy-expressions#feedback)
* Content Source: [articles/api-management/api-management-policy-expressions.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/api-management/api-management-policy-expressions.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by srvbpigh** [comment]
Hello, @MarkusMeyer13
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #40335](https://github.com/MicrosoftDocs/azure-docs/issues/40335) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @MarkusMeyer13 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/40335.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
