### ISSUE TITLE
IoTHubMessage_GetByteArray does not return NULL terminated strings - as the code implies

### ISSUE THREAD

**Issue by alaendle** [MicrosoftDocs/azure-docs.de-de#576]
https://github.com/MicrosoftDocs/azure-docs.de-de/blame/master/articles/iot-edge/tutorial-c-module-windows.md#L191
suggeriert, dass der String NULL terminiert ist - was er aber nicht ist - siehe https://github.com/Azure/azure-iot-sdk-c/issues/46.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 19ec7d5b-d1aa-9251-8246-2fb151d01537
* Version Independent ID: 0c5c183c-e8df-4e0c-c9c5-2c4f08149d3c
* Content: [Tutorial: Entwickeln eines C-Moduls für Windows – Azure IoT Edge](https://docs.microsoft.com/de-de/azure/iot-edge/tutorial-c-module-windows)
* Content Source: [articles/iot-edge/tutorial-c-module-windows.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-edge/tutorial-c-module-windows.md)
* Service: **iot-edge**
* GitHub Login: @shizn
* Microsoft Alias: **xshi**

**Comment by srvbpigh** [comment]
Hello, @alaendle
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #40520](https://github.com/MicrosoftDocs/azure-docs/issues/40520) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hallo, @alaendle  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/40520 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
