### ISSUE TITLE
Azure portal path not found

### ISSUE THREAD

**Issue by ezalex** [MicrosoftDocs/azure-docs.de-de#584]
I see no Azure Active Directory &gt; Authentication methods &gt; Authentication method policy (Preview) path in the portal.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ee6ac70d-5853-6a3a-0964-23b46910b4c4
* Version Independent ID: a5beda87-9845-8807-6221-7fdc64079587
* Content: [Aktivieren der kennwortlosen Anmeldung mit der Microsoft Authenticator-App (Vorschauversion) – Azure Active Directory](https://docs.microsoft.com/de-de/azure/active-directory/authentication/howto-authentication-passwordless-phone#feedback)
* Content Source: [articles/active-directory/authentication/howto-authentication-passwordless-phone.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/authentication/howto-authentication-passwordless-phone.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @ezalex
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ezalex** [comment]
Found it, in a different place:
**Security > Authentication methods - Authentication method policy (Preview)**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #41801](https://github.com/MicrosoftDocs/azure-docs/issues/41801) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @ezalex

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/41801

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
