### ISSUE TITLE
TLS/SSL configuration - very hard to understand what I need to to to use a "normal" MQTT client to connect

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/azure-docs.de-de#587]
I don't understand what I need to do to use an TLS/SSL connection using a "normal" MQTT Client like MQTT Explorer or MQTT.fx
I have now idea how and why to use TLS/SSL. I will read about it. 
But here in documentation is some python code where you explain how to use TLS/SSL. Should I write some python programs before I can connect with Azure IoT Hub?

I would prefer an easy instruction for dummies like me. Maybe also some links to the basics. 
I would like to be enabled to use an out-of-the-box MQTT client to connect with Azure IoT Hub without writing python code. 
I will learn python to connect to MQTT without the client. I promise. But not today.

It is very easy for me to connect to any other MQTT brokers without any TSL/SSL. But I am to stupid to understand how to connect to Azure IoT Hub.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bcf2a86a-1de0-2786-db87-58279ceffb22
* Version Independent ID: 7e43624f-a87d-1c4d-94e6-e38c1d42686f
* Content: [Grundlegendes zur Azure IoT Hub MQTT-Unterstützung](https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-mqtt-support)
* Content Source: [articles/iot-hub/iot-hub-mqtt-support.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-hub/iot-hub-mqtt-support.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robinsh**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @aisbergde 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/42267

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
