### ISSUE TITLE
Alphabetic navigation on the left shows "Salesforce" for this page instead of "Samanage"

### ISSUE THREAD

**Issue by 9songs** [MicrosoftDocs/azure-docs.de-de#588]
The link in the Navigation menu on the left should be "Samanage" instead of "Salesforce" for this page.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a9542543-ff14-b441-1e24-136c0108a9a3
* Version Independent ID: 756ea4f6-3274-fa69-93c7-808f36f8fef8
* Content: [Tutorial: Azure Active Directory-Integration mit Samanage](https://docs.microsoft.com/de-de/azure/active-directory/saas-apps/samanage-tutorial)
* Content Source: [articles/active-directory/saas-apps/samanage-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/saas-apps/samanage-tutorial.md)
* Service: **active-directory**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by srvbpigh** [comment]
Hello, @9songs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @9songs
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/azure/active-directory/saas-apps/samanage-tutorial

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
