### ISSUE TITLE
Funktion nicht aktiviert

### ISSUE THREAD

**Issue by kumbrink** [MicrosoftDocs/azure-docs.de-de#589]
Guten Tag,
Anscheinend ist diese Funktion nicht zulässig für alle Lizenzen. Solche Informationen sollten vielleicht in einer Nachricht zu einem Roll-Out enthalten sein bevor man lange Zeit darauf verbringt eine Funktion einzuschalten.
Viele Grüße

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ee217532-6b64-61f7-d965-bc95d9198cdb
* Version Independent ID: f6bab9a9-1b8b-01db-6e42-045eb04efe9e
* Content: [Einrichten des Ablaufs für Office 365-Gruppen – Azure Active Directory](https://docs.microsoft.com/de-de/azure/active-directory/users-groups-roles/groups-lifecycle#feedback)
* Content Source: [articles/active-directory/users-groups-roles/groups-lifecycle.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/users-groups-roles/groups-lifecycle.md)
* Service: **active-directory**
* Sub-service: **users-groups-roles**
* GitHub Login: @curtand
* Microsoft Alias: **curtand**

**Comment by srvbpigh** [comment]
Hello, @kumbrink
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Issue moved to [MicrosoftDocs/azure-docs #42645](https://github.com/MicrosoftDocs/azure-docs/issues/42645) via [**ZenHub**](https://www.zenhub.com/)

**Comment by v-maudel** [comment]
Hallo, @kumbrink 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/42645. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
