### ISSUE TITLE
cluster-issuer.yaml new apiVersion

### ISSUE THREAD

**Issue by glubb92** [MicrosoftDocs/azure-docs.de-de#593]
The provided apiVersion in the cluster-issuer.yaml example is not working anymore. Upgrade it to following version: cert-manager.io/v1alpha2 (tested with cert-manager version v0.11.0)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 12009c1f-282d-2632-fac0-64b09c432833
* Version Independent ID: 6052d3d4-d295-9340-b16d-4c200e34cd73
* Content: [Erstellen eines HTTP-Eingangscontrollers mit einer statischen IP-Adresse in Azure Kubernetes Service (AKS)](https://docs.microsoft.com/de-de/azure/aks/ingress-static-ip#feedback)
* Content Source: [articles/aks/ingress-static-ip.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/aks/ingress-static-ip.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @glubb92
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
@glubb92 

Vielen Dank für Ihr Feedback.  

Unsere Technikexperten haben sich Ihre Vorschläge angesehen und für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/azure/aks/ingress-static-ip#feedback.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

Mit freundlichen Grüßen  

das Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hallo, @glubb92,  

 

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: XXX.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

 

Mit freundlichen Grüßen  

das Microsoft DOCS International Team
