### ISSUE TITLE
cache store max-age header is not working

### ISSUE THREAD

**Issue by hendriksteinhorst** [MicrosoftDocs/azure-docs.de-de#598]
Using the code snipped for the max-age calculation in the cache store policy does not work for me. If the cache misses I get the following result:
"message": "Cache lookup resulted in a miss. Cache headers listed below were removed from the request to prompt the backend service to send back a complete response.",
    "cacheKey": omitted for brevity,
    "cacheHeaders": [
        {
            "name": "Cache-Control",
            "value": "max-age=10"
        }
    ]

This means the Cache-Control header is removed from the request. The script 
<cache-store duration="@{
    var header = context.Response.Headers.GetValueOrDefault("Cache-Control","");
    var maxAge = Regex.Match(header, @"max-age=(?<maxAge>\d+)").Groups["maxAge"]?.Value;
    return (!string.IsNullOrEmpty(maxAge))?int.Parse(maxAge):300;
  }"
 />

does not find the Cache-Control header and uses the default of 300 seconds. If I get a cache hit the cache-store is not executed.

Am I missing something?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 181c69b0-e136-426b-02f5-4a1a8f0f419d
* Version Independent ID: 2e57c2f1-fc01-17c9-cd94-920b582e6aa2
* Content: [Cacherichtlinien in Azure API Management](https://docs.microsoft.com/de-de/azure/api-management/api-management-caching-policies#feedback)
* Content Source: [articles/api-management/api-management-caching-policies.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/api-management/api-management-caching-policies.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by srvbpigh** [comment]
Hello, @hendriksteinhorst
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hendriksteinhorst

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43964

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
