### ISSUE TITLE
(German-version) Fehler bei der Bezeichnung in der Menüleiste

### ISSUE THREAD

**Issue by SimonOfHH** [MicrosoftDocs/azure-docs.de-de#599]
In der Menüleiste heißt dieser Punkt "DSC und Fenster" und ich vermute es soll "DSC und Windows" heißen 😉

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c2e15d16-5405-f4e9-e899-d4c74e418cad
* Version Independent ID: 00474e00-329e-772d-da02-c82c2c7a455a
* Content: [Azure-DSC-Erweiterungs-Handler (Desired State Configuration)](https://docs.microsoft.com/de-de/azure/virtual-machines/extensions/dsc-windows#feedback)
* Content Source: [articles/virtual-machines/extensions/dsc-windows.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/virtual-machines/extensions/dsc-windows.md)
* Service: **virtual-machines-windows**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by srvbpigh** [comment]
Hello, @SimonOfHH
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hallo, @SimonOfHH,   

Vielen Dank für Ihr Feedback.  

unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/azure/virtual-machines/extensions/dsc-windows#feedback.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

Mit freundlichen Grüßen  
das Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Hallo, @SimonOfHH ,  
  
Vielen Dank für Ihr Feedback. 
unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/azure/active-directory/develop/v2-permissions-and-consent#feedback.  
Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
