### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fhopfensperger** [MicrosoftDocs/azure-docs.de-de#600]
Thanks for the great feature. Does a roadmap exist for this feature? I would like to know when this feature is GA?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 31fa6bb5-4bc3-8e4d-e308-893e63d1f61a
* Version Independent ID: a228fbc5-3b98-02a5-bd89-7262886881cd
* Content: [Verwenden von Application Insights zum Überwachen Ihres Azure Kubernetes Service (AKS) oder anderer gehosteter Kubernetes-Anwendungen – Azure Monitor](https://docs.microsoft.com/de-de/azure/azure-monitor/app/kubernetes#feedback)
* Content Source: [articles/azure-monitor/app/kubernetes.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-monitor/app/kubernetes.md)
* Service: **azure-monitor**
* Sub-service: **application-insights**
* GitHub Login: @tokaplan
* Microsoft Alias: **alkaplan**

**Comment by srvbpigh** [comment]
Hello, @fhopfensperger
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @fhopfensperger,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
