### ISSUE TITLE
How to determine the certificates expiration date?

### ISSUE THREAD

**Issue by olivermue** [MicrosoftDocs/azure-docs.de-de#605]
Great to see, that it is so simple to replace the certificates. Nevertheless, I think it would be good to know, on how to find out how long the certificates are valid. Just to check, if the rotation has already been done or to plan till when the rotation has to be done.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9b78509d-73eb-6c32-aee1-9b34685a64ff
* Version Independent ID: 6f87cf70-1f5a-0f9e-862d-ae1436595f3b
* Content: [Rotieren von Zertifikaten in Azure Kubernetes Service (AKS)](https://docs.microsoft.com/de-de/azure/aks/certificate-rotation#feedback)
* Content Source: [articles/aks/certificate-rotation.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/aks/certificate-rotation.md)
* Service: **container-service**
* GitHub Login: @zr-msft
* Microsoft Alias: **zarhoads**

**Comment by srvbpigh** [comment]
Hello, @olivermue
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by zr-msft** [comment]
adding @sauryadas

**Comment by CeciAc** [comment]
Hello, @zr-msft

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/azure-docs/issues/44448 

For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
