### ISSUE TITLE
adminconsent endpoint requires also response_type parameter

### ISSUE THREAD

**Issue by thobach** [MicrosoftDocs/azure-docs.de-de#609]
When I call:
https://login.microsoftonline.com/common/v2.0/adminconsent?client_id=&lt;valid-clientt-id&gt;&state=12345&redirect_uri=https://localhost:1234&scope=https://graph.microsoft.com/.default

I'm forwarded to:
https://localhost:1234/?error=invalid_request&error_description=The%20provided%20request%20must%20include%20a%20%27response_type%27%20input%20parameter.&state=12345

The error message "The provided request must include a 'response_type' input parameter." Indicating the adminconsent endpoint also needs a response_type parameter, but it did not accept e.g. "token" or "code".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0ac43307-75d4-cb6f-e561-0dd9008f28c6
* Version Independent ID: 8fc47e76-5ee1-6aeb-73e2-c64c44e3e4ed
* Content: [Bereiche, Berechtigungen und Zustimmung für die Microsoft Identity Platform](https://docs.microsoft.com/de-de/azure/active-directory/develop/v2-permissions-and-consent#feedback)
* Content Source: [articles/active-directory/develop/v2-permissions-and-consent.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/develop/v2-permissions-and-consent.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @thobach
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @thobach, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/45151. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
