### ISSUE TITLE
Client Apps setting for mobile apps using MSAL

### ISSUE THREAD

**Issue by thiemf** [MicrosoftDocs/azure-docs.de-de#614]
Hi there, what would have to be selected in the section „Client Apps“ if I wanted to create a CA policy that targets mobile apps that use the MSAL SDK ?
Thank you.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 95d3af17-8d79-d9f3-a2f6-6860e4fe4493
* Version Independent ID: be8c1d1b-04e3-b880-c1f4-36f2b364ed73
* Content: [Referenz zu den Einstellungen für den bedingten Azure Active Directory-Zugriff](https://docs.microsoft.com/de-de/azure/active-directory/conditional-access/technical-reference#feedback)
* Content Source: [articles/active-directory/conditional-access/technical-reference.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/conditional-access/technical-reference.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @thiemf
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MicrosoftGuyJFlo** [comment]
If the app is registered in Azure AD then you would reference that app specifically under cloud apps and actions. 

https://docs.microsoft.com/azure/active-directory/manage-apps/plan-an-application-integration

**Comment by ticianaciminari** [comment]
Hello, @thiemf,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
