### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by Gerrilicious** [MicrosoftDocs/azure-docs.de-de#616]
Hi, it seems the Images for this page are missing as i only see the Markdown notation and not the image.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c5694a0e-53c2-4b8f-fc65-15b56b0e8f11
* Version Independent ID: 6bd8853e-6134-3488-39d0-b294e933dc89
* Content: [Beschreiben eines Clusters mithilfe des Clusterressourcen-Managers](https://docs.microsoft.com/de-de/azure/service-fabric/service-fabric-cluster-resource-manager-cluster-description#feedback)
* Content Source: [articles/service-fabric/service-fabric-cluster-resource-manager-cluster-description.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/service-fabric/service-fabric-cluster-resource-manager-cluster-description.md)
* GitHub Login: @masnider
* Microsoft Alias: **masnider**

**Comment by srvbpigh** [comment]
Hello, @Gerrilicious
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @Gerrilicious,

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @Gerrilicious, 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @Gerrilicious, 

Thanks once again for your comment. 

Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future. 

Kind regards, 

Microsoft DOCS International Team
