### ISSUE TITLE
Azure Functions 2.x recommended?

### ISSUE THREAD

**Issue by K232** [MicrosoftDocs/azure-docs.de-de#618]
In https://docs.microsoft.com/de-de/azure/azure-functions/functions-create-your-first-function-visual-studio#create-a-function-app-project it says that Azure Functions 2.x is recommended, at least for creating a first function. Is this still the actual recommendation? If so, why shouldn't 3.x be used? I could not find any disadvantages of 3.x (except that VS 16.4 is maybe not installed), especially as moving from 2.x to 3.x seems to be much easier than from 1.x to 2.x.

Many thanks!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6e88ea08-81ef-2b5a-b9d6-539e85592672
* Version Independent ID: f2d8b7b4-906a-d1f5-5201-fc22a7890955
* Content: [Erstellen Ihrer ersten Funktion in Azure mit Visual Studio](https://docs.microsoft.com/de-de/azure/azure-functions/functions-create-your-first-function-visual-studio)
* Content Source: [articles/azure-functions/functions-create-your-first-function-visual-studio.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-functions/functions-create-your-first-function-visual-studio.md)

**Comment by srvbpigh** [comment]
Hello, @K232
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47689](https://github.com/MicrosoftDocs/azure-docs/issues/47689) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @K232, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47689. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
