### ISSUE TITLE
Outdated Screenshot

### ISSUE THREAD

**Issue by K232** [MicrosoftDocs/azure-docs.de-de#619]
Screenshot at https://docs.microsoft.com/de-de/azure/includes/media/functions-run-function-test-local-vs/functions-run-browser-local-vs.png in https://docs.microsoft.com/de-de/azure/azure-functions/functions-create-your-first-function-visual-studio#run-the-function-locally is outdated. It says, the return value should be: "Hello Glenn". In fact, it is: Hello, Glenn
I was not able to update the screenshot as https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/includes/media/functions-run-function-test-local-vs/functions-run-browser-local-vs.png is not found, and you of course have a global guideline how to mark screenshots etc. so it's probably better you update the screenshot.

Many thanks!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6e88ea08-81ef-2b5a-b9d6-539e85592672
* Version Independent ID: f2d8b7b4-906a-d1f5-5201-fc22a7890955
* Content: [Erstellen Ihrer ersten Funktion in Azure mit Visual Studio](https://docs.microsoft.com/de-de/azure/azure-functions/functions-create-your-first-function-visual-studio#create-a-function-app-project)
* Content Source: [articles/azure-functions/functions-create-your-first-function-visual-studio.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-functions/functions-create-your-first-function-visual-studio.md)

**Comment by srvbpigh** [comment]
Hello, @K232
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47693](https://github.com/MicrosoftDocs/azure-docs/issues/47693) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @K232, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47693. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
