### ISSUE TITLE
Post SAMLRequest without login

### ISSUE THREAD

**Issue by rpeters-gom** [MicrosoftDocs/azure-docs.de-de#620]
Hi there,

I want to paste the SAMLRequest automatic and have no possibility to login then.
I tried to create some Azure AD login with an access_token but this will be ignored when POST SAMLRequest with it as Authorization.

How can I get an access_token to skip the login page and directly get the SAMLResponse?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 62bb99a4-4092-0202-48bf-4e61ee424faf
* Version Independent ID: a066de9a-42fb-2fcc-683d-2ffdc45fdf3d
* Content: [Azure-SAML-Protokoll für einmaliges Anmelden](https://docs.microsoft.com/de-de/azure/active-directory/develop/single-sign-on-saml-protocol#feedback)
* Content Source: [articles/active-directory/develop/single-sign-on-saml-protocol.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/develop/single-sign-on-saml-protocol.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @rpeters-gom
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @rpeters-gom 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
