### ISSUE TITLE
git push azure master fails 

### ISSUE THREAD

**Issue by alrabe** [MicrosoftDocs/azure-docs.de-de#625]
"remote: Error: Platform 'dotnet' version '3.1' is unsupported. Supported versions: 1.0.16, 1.1.14, 2.0.9, 2.1.13, 2.2.7, 3.0.0"

even when changing the framework version from 3.1 to 3.0 in the project file

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8460864c-a2ad-b8e5-d1fc-6135a30edfdc
* Version Independent ID: 43f15878-2497-ca3a-324b-9f4b2e9c76dc
* Content: [Schnellstart: Ausführen einer Linux-ASP.NET Core-App](https://docs.microsoft.com/de-de/azure/app-service/containers/quickstart-dotnetcore#feedback)
* Content Source: [articles/app-service/containers/quickstart-dotnetcore.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/app-service/containers/quickstart-dotnetcore.md)

**Comment by srvbpigh** [comment]
Hello, @alrabe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by alrabe** [comment]
Hi. I think I overlook that in the example an .NET Core 2.2 based web app is used. I created a 3.1 web app using the Azure web page.
