### ISSUE TITLE
Connected Service Secure Secrets With Azure Key Vault not found

### ISSUE THREAD

**Issue by drunkdev1991** [MicrosoftDocs/azure-docs.de-de#628]
Hello folks,

I was following this doc, but did not find the "Secure Secrets With Azure Key Vault" connected service in the Marketplace or installed.
I am using VS2019 v16.4.5, MS.Net Framework v4.8.03752, my project is .NET Core 2.1

Is there currently an issue within the decription? How do I install this?
Any hint is welcome!

Cheers!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 776dc3e0-fe6e-fdf5-15c0-5d32feeec553
* Version Independent ID: 8378b453-8238-91e5-4dff-eb5f6c6be83a
* Content: [Hinzufügen von Key Vault-Unterstützung zu Ihrem ASP.NET-Projekt mit Visual Studio: Azure Key Vault](https://docs.microsoft.com/de-de/azure/key-vault/vs-key-vault-add-connected-service#feedback)
* Content Source: [articles/key-vault/vs-key-vault-add-connected-service.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/key-vault/vs-key-vault-add-connected-service.md)
* Service: **key-vault**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by srvbpigh** [comment]
Hello, @drunkdev1991
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ghogen** [comment]
@drunkdev1991 It shows up for me with the ASP.NET Core project type with Visual Studio 2019 16.3 and later builds.  What project type are you using?  The Connected Services available do depend on the project type.

**Comment by drunkdev1991** [comment]
@ghogen Yes, I checked it, for a new ASP.NET Core project it is showing up for me too. But, here I am running the project template for "Azure Functions".  Indeed the connected service for Azure KV does not show up then if I start another of those projects.
Is there a reason, why this connected service is disabled for the "Azure Functions" project template? Downunder, it is a .NET Core project...

**Comment by ghogen** [comment]
I will contact the engineering team and get their response to this.  If they add support, of course I will update the document.  In the meantime, we'll close this issue as it's not a doc issue.  You can also request the feature on [Dev Community]https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by ghogen** [comment]
#please-close
