### ISSUE TITLE
Code inclusions don't work when viewing the page in German

### ISSUE THREAD

**Issue by chlandsi** [MicrosoftDocs/azure-docs.de-de#629]
Under "Display the recognition results (or errors)" and "Check your code", I don't see the included code, but markup like this `Inside the using statement, add this code: [!code-csharp]` when viewing the page in German (de-de in the url). The index on the left is in German, as well as the boilerplate text in the main pane, but the content is in English. Code includes work as expected when viewing the page in English.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e4b55e56-55a1-d635-6bea-271dc361d676
* Version Independent ID: 8e9cb28f-c133-f310-3c7d-3a3b7e85f69d
* Content: [Schnellstart: Erkennen von Spracheingaben per Mikrofon – Speech-Dienst - Azure Cognitive Services](https://docs.microsoft.com/de-de/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-microphone?tabs=dotnet%2Cx-android%2Clinux%2Cjava-runtime&pivots=programming-language-csharp#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/quickstarts/speech-to-text-from-microphone.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cognitive-services/Speech-Service/quickstarts/speech-to-text-from-microphone.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by srvbpigh** [comment]
Hello, @chlandsi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49897](https://github.com/MicrosoftDocs/azure-docs/issues/49897) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @chlandsi, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/49897. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
