### ISSUE TITLE
Wrong key size for private key in Azure P2S VPN Linux guide

### ISSUE THREAD

**Issue by raidlman** [MicrosoftDocs/azure-docs.de-de#631]
According to https://docs.microsoft.com/en-us/azure/vpn-gateway/point-to-site-about#certsettings client certificates should be generated with 4096 bits key length.

### Issue
Both guides on https://docs.microsoft.com/de-de/azure/vpn-gateway/vpn-gateway-certificates-point-to-site-linux and https://docs.microsoft.com/de-de/azure/vpn-gateway/point-to-site-vpn-client-configuration-azure-cert#generate-certificates do not explicitly define the key length when generating the certificate.

The ipsec tool on Ubuntu 18.04 generates certificates with the default key length 2048:

```
# ipsec pki --gen --help
strongSwan 5.6.2 PKI tool
usage:
  pki --gen [--type rsa|ecdsa|ed25519|bliss] [--size bits] [--safe-primes]
            [--shares n] [--threshold l] [--outform der|pem]
        --help            (-h)  show usage information
        --type            (-t)  type of key, default: rsa
        --size            (-s)  keylength in bits, default: rsa 2048, ecdsa 384, bliss 1
        --safe-primes     (-p)  generate rsa safe primes
        --shares          (-n)  number of private rsa key shares
        --threshold       (-l)  minimum number of participating rsa key shares
        --outform         (-f)  encoding of generated private key, default: der
        --debug           (-v)  set debug level, default: 1
        --options         (-+)  read command line options from file
```

### Result
Strongswan fails with

```
...
parsed IKE_AUTH response 8 [ EAP/REQ/TLS ]
received fatal TLS alert 'access denied'
EAP_TLS method failed
generating INFORMATIONAL request 9 [ N(AUTH_FAILED) ]
...
```

when doing an `ipsec up azure`.

### Solution
Change documentation to

```
ipsec pki --gen --size 4096 --outform pem > caKey.pem
```

You can also refer to this excellent guide to improve your doumentation http://wiki.ciscolinux.co.uk/index.php?title=Azure/Point-to-Site_VPN.

**Comment by srvbpigh** [comment]
Hello, @raidlman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50248](https://github.com/MicrosoftDocs/azure-docs/issues/50248) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @raidlman, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50248. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
