### ISSUE TITLE
Docs? And how to get Get-AutomationPSCredential running in the Az Module?

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/azure-docs.de-de#632]
Hello

Because the Online Azure Editors (e.g. the PowerShell Script Editor in Azure Automation Runbook) is a shame (it does not offer much more than a syntax highlighting), we're required to use the desktop PowerShell with Connect-AzAccount and the Az Module to be productive and not spend days and use try & error to get simple scripts running.

This Page here is called "Docs".
Why does it not help to get started, so that we can use Get-AutomationPSCredential in desktop PowerShell?

Thanks a lot, kind regards,
Thomas

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2f830218-a56b-6a7e-d6e7-7736896d3f91
* Version Independent ID: ae33d704-d0b7-d478-8602-cc787f706d72
* Content: [Anmeldeinformationsobjekte in Azure Automation](https://docs.microsoft.com/de-de/azure/automation/shared-resources/credentials#feedback)
* Content Source: [articles/automation/shared-resources/credentials.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/automation/shared-resources/credentials.md)
* Service: **automation**
* Sub-service: **shared-capabilities**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by srvbpigh** [comment]
Hello, @schittli
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50331](https://github.com/MicrosoftDocs/azure-docs/issues/50331) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @schittli, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50331. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
