### ISSUE TITLE
Many errors on the page, making it really hard and time consuming to fix an unbootable VM

### ISSUE THREAD

**Issue by mimergel** [MicrosoftDocs/azure-docs.de-de#634]
Hi, Please correct/improve the documentation. Thanks, Michael

wrong:
$snapshotId=(az snapshot show --name $snapshot --resource-group $resourceGroup --query [id] -o tsv)
correct: 
$snapshotId=(az snapshot show --name $snapshot --resource-group $resourceGroup --query id -o tsv)

wrong:
$myNewOSDiskid=(az vm show -g myResourceGroupDisk -n myNewOSDisk --query "storageProfile.osDisk.managedDisk.id" -o tsv)
correct:
$myNewOSDiskid=(az disk show -g myResourceGroupDisk -n myNewOSDisk --query id -o tsv)

wrong:
# Attach the disk to the troubleshooting VM
az vm disk attach --disk $diskId --resource-group MyResourceGroup --size-gb 128 --sku Standard_LRS --vm-name MyTroubleshootVM
correct:
az vm disk attach --name $myNewOSDiskid --resource-group MyResourceGroup --size-gb $diskSize --sku $storageType --vm-name MyTroubleshootVM

wrong:
# Get ID of the OS disk that is repaired.
$myNewOSDiskid=(az vm show -g myResourceGroupDisk -n myNewOSDisk --query "storageProfile.osDisk.managedDisk.id" -o tsv)
correct:
$myNewOSDiskid=(az disk show -g $MyResourceGroup -n $osDisk --query id -o tsv)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7e316b71-dc85-c234-fdc9-5b9a8e0af883
* Version Independent ID: 64001855-609b-9691-d7c4-069743919fd3
* Content: [Verwenden eines virtuellen Linux-Computers zur Problembehandlung mithilfe der Azure CLI](https://docs.microsoft.com/de-de/azure/virtual-machines/troubleshooting/troubleshoot-recovery-disks-linux)
* Content Source: [articles/virtual-machines/troubleshooting/troubleshoot-recovery-disks-linux.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/virtual-machines/troubleshooting/troubleshoot-recovery-disks-linux.md)
* Service: **virtual-machines-linux**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by srvbpigh** [comment]
Hello, @mimergel
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @mimergel, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50529. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
