### ISSUE TITLE
Repo not available

### ISSUE THREAD

**Issue by locherro** [MicrosoftDocs/azure-docs.de-de#635]
"https://github.com/Azure-Samples/iot-hub-node-raspberrypi-client-app" is not available

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a57d05c9-562c-02a5-7ccd-b1b1bb7c8f0c
* Version Independent ID: 17ee094f-aee3-ca0c-959b-6380e4ea8b89
* Content: [Verbinden von Raspberry Pi mit Azure IoT Hub in der Cloud (Node.js)](https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-raspberry-pi-kit-node-get-started#feedback)
* Content Source: [articles/iot-hub/iot-hub-raspberry-pi-kit-node-get-started.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-hub/iot-hub-raspberry-pi-kit-node-get-started.md)
* Service: **iot-hub**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by srvbpigh** [comment]
Hello, @locherro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50717](https://github.com/MicrosoftDocs/azure-docs/issues/50717) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @locherro, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50717. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by wesmc7777** [comment]
We are using a new sample repo for this article ([https://github.com/Azure-Samples/azure-iot-samples-node.git](https://github.com/Azure-Samples/azure-iot-samples-node.git)). Please see the[ US version of this How-To topic](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-raspberry-pi-kit-node-get-started#set-up-raspberry-pi). I don't think the other language specific versions have been updated yet.
