### ISSUE TITLE
Unattended Installation

### ISSUE THREAD

**Issue by marcelkmfst** [MicrosoftDocs/azure-docs.de-de#636]
It is possible to perform unattended installation of the client by using ESD solutions like intune by importing the config file over the command line:

azurevpn -i azurevpnconfig.xml  

Note:
You will have to ensure that the XML is in the “C:\Users\%username%\AppData\Local\Packages\Microsoft.AzureVpn_8wekyb3d8bbwe\LocalState” folder.

Can we please add this to the official documentation?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e9ef898a-0b72-e018-8a3d-6f14f62e1119
* Version Independent ID: b62b5b8f-bc88-0868-a2f6-1020a5097460
* Content: [VPN Gateway: VPN-Client für OpenVPN-P2S-Protokollverbindungen: Azure AD-Authentifizierung](https://docs.microsoft.com/de-de/azure/vpn-gateway/openvpn-azure-ad-client)
* Content Source: [articles/vpn-gateway/openvpn-azure-ad-client.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/vpn-gateway/openvpn-azure-ad-client.md)
* Service: **vpn-gateway**
* GitHub Login: @anzaman
* Microsoft Alias: **alzam**

**Comment by srvbpigh** [comment]
Hello, @marcelkmfst
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50798](https://github.com/MicrosoftDocs/azure-docs/issues/50798) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @marcelkmfst, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/50798. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
