### ISSUE TITLE
Forced Tunneling

### ISSUE THREAD

**Issue by marcelkmfst** [MicrosoftDocs/azure-docs.de-de#637]
More information about Force Tunneling configuraiton is required. e.g. specifying the 0.0.0.0/0 route will not work as there is usually a default route with a lower metric already in the system. For me it worked to include a route of 0.0.0.0/1. We also have to describe implications when other VPNs are already present in the system. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e9ef898a-0b72-e018-8a3d-6f14f62e1119
* Version Independent ID: b62b5b8f-bc88-0868-a2f6-1020a5097460
* Content: [VPN Gateway: VPN-Client für OpenVPN-P2S-Protokollverbindungen: Azure AD-Authentifizierung](https://docs.microsoft.com/de-de/azure/vpn-gateway/openvpn-azure-ad-client)
* Content Source: [articles/vpn-gateway/openvpn-azure-ad-client.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/vpn-gateway/openvpn-azure-ad-client.md)
* Service: **vpn-gateway**
* GitHub Login: @anzaman
* Microsoft Alias: **alzam**

**Comment by srvbpigh** [comment]
Hello, @marcelkmfst
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @marcelkmfst , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
