### ISSUE TITLE
Error unknown by uploading new train Data to custom vision

### ISSUE THREAD

**Issue by TiMeJuMp** [MicrosoftDocs/azure-docs.de-de#638]
Hi, I'll try to upload some train data in batch processing (max 64 images) to Custom Vision portal. My Project is already created, so I have added the project Id, key and Endpoint correctly. 

After I want to upload via "trainApi.CreateImagesFromFiles(id, new ImageFileCreateBatch(imageFileEntries));" I get for each image I want to upload an ErrorUnknown and the complete Batch is declined.

What does ErrorUnknown mean in this scenario? 

Thanks Christian

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ae543de4-ff83-fce7-56e9-4bc8aab79455
* Version Independent ID: 8f2ee4be-74e3-1350-7be1-d38a04764249
* Content: [Schnellstart: Erstellen eines Objekterkennungsprojekts mit dem SDK für C# – Custom Vision - Azure Cognitive Services](https://docs.microsoft.com/de-de/azure/cognitive-services/custom-vision-service/csharp-tutorial-od)
* Content Source: [articles/cognitive-services/Custom-Vision-Service/csharp-tutorial-od.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cognitive-services/Custom-Vision-Service/csharp-tutorial-od.md)
* Service: **cognitive-services**
* Sub-service: **custom-vision**
* GitHub Login: @areddish
* Microsoft Alias: **areddish**

**Comment by srvbpigh** [comment]
Hello, @TiMeJuMp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by TiMeJuMp** [comment]
Okay found the issue. 
Please check your tag GUIDs if they are correct.
Probably with code. 
var tags = trainingApi.GetTags(id);
Just copied the wrong ones from the UI...

Can be closed. :)

**Comment by CeciAc** [comment]
Hello, @TiMeJuMp 
Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations. 
We encourage you to provide your valuable feedback so that we can continue improve your experience. 

Kind regards, 

Microsoft DOCS International Team
