### ISSUE TITLE
Procedure to create self signed certificate results in error AADB2C90022 when downloading the metadata

### ISSUE THREAD

**Issue by gregorwolf** [MicrosoftDocs/azure-docs.de-de#639]
Hello Azure B2C Team,

I've followed the procedure in section:

https://docs.microsoft.com/de-de/azure/active-directory-b2c/connect-with-saml-service-providers#11-prepare-a-self-signed-certificate

to create the self signed certificate. Unfortunately this results in the error AADB2C90022 when downloading the metadata. The detailed error message is:

"unable to return metadata for the policy 'B2C_1A_signup_signin_saml' in tenant 'tenant-name.onmicrosoft.com'"

As soon as I've created the certificate using https://github.com/FiloSottile/mkcert and uploaded it to the Policy Keys the error was gone and I was able to download the SAML Metadata.

Best regards
Gregor

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1376f79b-474f-4b83-2583-07acd2eeb2f4
* Version Independent ID: 45d314dd-c9fa-50a5-cb39-d34db80c7874
* Content: [Konfigurieren von Azure AD B2C als SAML-IDP für Ihre Anwendungen](https://docs.microsoft.com/de-de/azure/active-directory-b2c/connect-with-saml-service-providers#11-prepare-a-self-signed-certificate)
* Content Source: [articles/active-directory-b2c/connect-with-saml-service-providers.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory-b2c/connect-with-saml-service-providers.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by srvbpigh** [comment]
Hello, @gregorwolf
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello,  @gregorwolf

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team

**Comment by gregorwolf** [comment]
Dear @CeciAc ,
I still think it is a documentation issue. Because if a different way to create the certificate is used then the product works. 
Best regards
Gregor
