### ISSUE TITLE
New "Microsoft Office" app

### ISSUE THREAD

**Issue by identityiskey** [MicrosoftDocs/azure-docs.de-de#640]
Please add that also the new "Microsoft Office" app is supported for Certificate Based Authentication. Works perfect on iOS!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c10a5c09-7cc9-c96c-f7d1-913dd5d1a58f
* Version Independent ID: 883b7411-6072-b686-9ba9-2307c1430f2e
* Content: [Zertifikatbasierte Authentifizierung unter iOS – Azure Active Directory](https://docs.microsoft.com/de-de/azure/active-directory/authentication/active-directory-certificate-based-authentication-ios#feedback)
* Content Source: [articles/active-directory/authentication/active-directory-certificate-based-authentication-ios.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/authentication/active-directory-certificate-based-authentication-ios.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by srvbpigh** [comment]
Hello, @identityiskey
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #51807](https://github.com/MicrosoftDocs/azure-docs/issues/51807) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @identityiskey, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/51807. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
