### ISSUE TITLE
What is the License Code for "Microsoft 365 Phone System"?

### ISSUE THREAD

**Issue by stumbaumr** [MicrosoftDocs/azure-docs.de-de#643]
Tried to use Powershell to assign "Microsoft 365 Phone System"-License to specific userPrincipalName and failed. There seems to be no working documentation on how to do this.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Produktnamen und Serviceplanbezeichner für die Lizenzierung – Azure AD](https://docs.microsoft.com/de-de/azure/active-directory/users-groups-roles/licensing-service-plan-reference)
* Content Source: [articles/active-directory/users-groups-roles/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/users-groups-roles/licensing-service-plan-reference.md)
* Service: **active-directory**
* Sub-service: **users-groups-roles**
* GitHub Login: @ajayanti1
* Microsoft Alias: **arjay**

**Comment by srvbpigh** [comment]
Hello, @stumbaumr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52008](https://github.com/MicrosoftDocs/azure-docs/issues/52008) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @stumbaumr, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52008. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
