### ISSUE TITLE
Register Model fails

### ISSUE THREAD

**Issue by kato-m** [MicrosoftDocs/azure-docs.de-de#644]
The code in the section 'Save and register Model' doesn't seem to work in a pipeline. Replacins the extension '.joblib' by '.pkl' wotks, though. Saying this,  it would be helpful to mention that only pickled models (suffix .pkl) are supported and no zipped pickles. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f70a36b8-6b3b-e06c-84d6-33fd56f79ea7
* Version Independent ID: fd3dc619-fc56-5f93-860b-997c2eeb44f4
* Content: [Trainieren von Scikit-learn-Machine Learning-Modellen - Azure Machine Learning](https://docs.microsoft.com/de-de/azure/machine-learning/how-to-train-scikit-learn#feedback)
* Content Source: [articles/machine-learning/how-to-train-scikit-learn.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/machine-learning/how-to-train-scikit-learn.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @maxluk
* Microsoft Alias: **maxluk**

**Comment by srvbpigh** [comment]
Hello, @kato-m
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52073](https://github.com/MicrosoftDocs/azure-docs/issues/52073) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @kato-m, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52073. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
