### ISSUE TITLE
German translation: One sentence doesn't make sense

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/azure-docs.de-de#646]
<blockquote>
- Distributed across Availability Zones (as well regions) in locations that have multiple Availability Zones.
</blockquote>

... is incorrectly translated into German:

<blockquote>
- Sie sind an Standorten mit mehreren Verfügbarkeitszonen über Verfügbarkeitszonen (sowie Regionen) verteilt.
</blockquote>

The causal relation between "locations that have multiple Availability Zones" and "Distributed across Availability Zones (as well regions)" is missing in the German translation.

I suggest it to read like this:

<blockquote>
- An Standorten mit mehreren Verfügbarkeitszonen sind sie über diese Verfügbarkeitszonen (sowie deren Regionen) verteilt.
</blockquote>

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bef92944-e84a-bda9-13d8-e537ede110fc
* Version Independent ID: 1879e7a2-8c60-06a8-fc44-3bfbbb9802f9
* Content: [Übersicht](https://docs.microsoft.com/de-de/azure/azure-resource-manager/management/overview#terminology)
* Content Source: [articles/azure-resource-manager/management/overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-resource-manager/management/overview.md)

**Comment by srvbpigh** [comment]
Hello, @SetTrend
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SetTrend 

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/azure/azure-resource-manager/management/overview#terminology  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
