### ISSUE TITLE
Access Datastore from Train Script

### ISSUE THREAD

**Issue by philippschaefer4** [MicrosoftDocs/azure-docs.de-de#649]
Hey, 
is there any other way to access data on a datastore than creating a dataset as it is described above? Is it perhaps possible to mount the datastore as storage?

There is probably the possibility to login to your workspace, get the datastore and download the data. But that seems not a good option.

And if it is possible: does it make any sense or should you always encapsulate your data in a dataset?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: cd91721f-4a86-30cb-5e37-147c7319f0e6
* Version Independent ID: 98499c4f-ad83-81a4-e5db-af6415f79a98
* Content: [Herstellen einer Verbindung mit Azure-Speicherdiensten - Azure Machine Learning](https://docs.microsoft.com/de-de/azure/machine-learning/how-to-access-data)
* Content Source: [articles/machine-learning/how-to-access-data.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/machine-learning/how-to-access-data.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @MayMSFT
* Microsoft Alias: **sihhu**

**Comment by srvbpigh** [comment]
Hello, @philippschaefer4
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52678](https://github.com/MicrosoftDocs/azure-docs/issues/52678) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @philippschaefer4,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/52678.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
