### ISSUE TITLE
Use MySQL/PostgreSQL Indexer

### ISSUE THREAD

**Issue by boredom2** [MicrosoftDocs/azure-docs.de-de#650]
Hi there,

I know, that there is a Private Preview for an Indexer via MySQL. As far as I know, this Preview is lasting since quite a Time.
Are there any Plans to release this to GA soon?
Or has it been canceled?

Thanks!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7a012c5b-57eb-0072-3258-2272d6dbfbfb
* Version Independent ID: e9320b7d-f6c4-7423-64d4-81a5c056a128
* Content: [Indexer für das Crawlen von Daten während des Imports - Azure Cognitive Search](https://docs.microsoft.com/de-de/azure/search/search-indexer-overview)
* Content Source: [articles/search/search-indexer-overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/search/search-indexer-overview.md)
* Service: **cognitive-search**
* GitHub Login: @HeidiSteen
* Microsoft Alias: **heidist**

**Comment by srvbpigh** [comment]
Hello, @boredom2
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by HeidiSteen** [comment]
@boredom2 Hi, it's not cancelled.  I'll check with the feature owner to see if he can share a roadmap.

**Comment by HeidiSteen** [comment]
@boredom2 Sorry, but there is no timeline for either a public preview or GA announcement at this time.  

#please-close
