### ISSUE TITLE
error: Cannot read property 'promise' of undefined

### ISSUE THREAD

**Issue by PapillonZ** [MicrosoftDocs/azure-docs.de-de#652]
When following the tutorial on VSCode and Azure Machine Learning I get an error when I try to create a computer node: error: Cannot read property 'promise' of undefined. This prevents me from creating a computer node in VSCode with Azure Machine Learning. I use the MINST example. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e548a903-7aa0-75a2-1c43-afa48dbbc7ea
* Version Independent ID: 21566e3a-f540-3a98-3c61-e598c4e6ac0b
* Content: [Tutorial: Trainieren und Bereitstellen eines Modells unter Verwendung der Visual Studio Code-Erweiterung - Azure Machine Learning](https://docs.microsoft.com/de-de/azure/machine-learning/tutorial-train-deploy-image-classification-model-vscode#feedback)
* Content Source: [articles/machine-learning/tutorial-train-deploy-image-classification-model-vscode.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/machine-learning/tutorial-train-deploy-image-classification-model-vscode.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by srvbpigh** [comment]
Hello, @PapillonZ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #53616](https://github.com/MicrosoftDocs/azure-docs/issues/53616) via [**ZenHub**](https://www.zenhub.com/)
