### ISSUE TITLE
Generate Client Certificate

### ISSUE THREAD

**Issue by Broker80** [MicrosoftDocs/azure-docs.de-de#655]
Leider funktioniert bei mir die Generierung eines Clientzertifikates aus einem "Selfsigning Zertifikat" nicht.

Istzustand:
Ich habe ein Selfsigning-CA-Zertifikat mittels www.selfsignedcertificate.com für ein QNAP-NAS erzeugt.
Dieses Zertifikat habe ich auf dem NAS installiert und mit den vorhandenen Tools extrahiert und in die "vertrauenswürdigen-Stammzertifizierungsstellen auf meinem Windows PC exportiert.
Nun geht es darum, basierent auf diesem Zertifikat ein Clientzertifikat zu erzeugen.
Die Schritte 1, 2 ,3 funktionieren.

Ergebnis zu 1:
PS C:\Users\Ralf.AZ-RALF-ADMIN&gt; Get-ChildItem -Path "Cert:\CurrentUser\my"

   PSParentPath: Microsoft.PowerShell.Security\Certificate::CurrentUser\my

Thumbprint                                Subject
----------                                -------
F0BD97B4EC6CD8B71C35631738259CF9F2E54381  CN=Adobe Content Certificate 10-5, OU=Cloud Technology, O=Adobe Systems, L=San Jose, S=California, C=US
D1DF7F06B769BCCB3F4479041EC1F06E9CD3CB1A  CN=Adobe Intermediate CA 10-3, OU=Cloud Technology, O=Adobe Systems, L=San Jose, S=California, C=US
BF89E52F8D681360E6B84941BD2F9BC0093309F6  CN=Adobe Intermediate CA 10-4, OU=Cloud Technology, O=Adobe Systems, L=San Jose, S=California, C=US
B469F924992E0712E9025D291AB4353FEC4FCE33  CN=CLOUDSERVER
906CC149415780CFB79F39E1CF449F87CA6D4D16  CN=Adobe Content Certificate 10-6, OU=Cloud Technology, O=Adobe Systems, L=San Jose, S=California, C=US

Ergebnis zu 3:

PS C:\Users\Ralf.AZ-RALF-ADMIN&gt; $cert = Get-ChildItem -Path "Cert:\CurrentUser\My\B469F924992E0712E9025D291AB4353FEC4FCE33"
PS C:\Users\Ralf.AZ-RALF-ADMIN&gt;

Bei 4 gibt es folgende Fehlermeldung:

New-SelfSignedCertificate : Dem Zertifikat fehlt eine Eigenschaft, die auf einen privaten Schlüssel verweist. 0x8009200a (-2146885622 CRYPT_E_UNEXPECTED_MSG_TYPE) CertEnroll::CSignerCertificate::Initialize: Das Objekt oder die Eigenschaft
wurde nicht gefunden. 0x80092004 (-2146885628 CRYPT_E_NOT_FOUND)
In Zeile:1 Zeichen:1
+ New-SelfSignedCertificate -Type Custom -DnsName P2SChildCert -KeySpec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-SelfSignedCertificate], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.CertificateServices.Commands.NewSelfSignedCertificateCommand

Könnte mir da bitte jemand helfen? Ich bin nicht so vertraut mit Powershell.

Ich möchte das clientzertifikat anschließend exportieren und z.B. auf einem Mobile Phone einsetzen.

Vielen Dank

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 63df9645-af2c-3cfc-8f65-413912d88efe
* Version Independent ID: d2edf564-2c83-f1da-dbf0-dbc41c4948bf
* Content: [Generieren und Exportieren von Zertifikaten für P2S: PowerShell - Azure VPN Gateway](https://docs.microsoft.com/de-de/azure/vpn-gateway/vpn-gateway-certificates-point-to-site#feedback)
* Content Source: [articles/vpn-gateway/vpn-gateway-certificates-point-to-site.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/vpn-gateway/vpn-gateway-certificates-point-to-site.md)
* Service: **vpn-gateway**
* GitHub Login: @cherylmc
* Microsoft Alias: **cherylmc**

**Comment by srvbpigh** [comment]
Hello, @Broker80
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Broker80** [comment]
Thank you very much,

please notice, that I did not create the selfsigning certificate on the windows system.
I took a selfsigning certificate from another source.

Best Regards

Ralf Schubert

 

Von: srvbpigh <notifications@github.com> 
Gesendet: Freitag, 1. Mai 2020 18:28
An: MicrosoftDocs/azure-docs.de-de <azure-docs.de-de@noreply.github.com>
Cc: Broker80 <Ralf_Schubert@yahoo.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/azure-docs.de-de] Generate Client Certificate (#655)

 

Hello, @Broker80 <https://github.com/Broker80> 

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54001](https://github.com/MicrosoftDocs/azure-docs/issues/54001) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @Broker80,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/54001.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
