### ISSUE TITLE
SAS für Blob Container im ADLS Gen2 

### ISSUE THREAD

**Issue by darayavah** [MicrosoftDocs/azure-docs.de-de#656]
Hallo, 
für ein Storage Account im ADLS Gen2 kann man ein Shared Acces Signature erstellen. 
Dies kann man jedoch nicht für ein Blob Container im Storage Account machen.
Bei einem normalen Storage Account (nicht in ADLS Gen2 ist dies jedoch möglich) 
Warum ist das so? 
Vielen Dank im Voraus

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9d29fd9c-d764-3d15-bff3-2d61ec9f757f
* Version Independent ID: 58503de5-d10f-eb43-34f9-6f72a0fa1f9b
* Content: [Übersicht über die Zugriffssteuerung in Azure Data Lake Storage Gen2](https://docs.microsoft.com/de-de/azure/storage/blobs/data-lake-storage-access-control)
* Content Source: [articles/storage/blobs/data-lake-storage-access-control.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/storage/blobs/data-lake-storage-access-control.md)
* Service: **storage**
* Sub-service: **data-lake-storage-gen2**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by srvbpigh** [comment]
Hello, @darayavah
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54888](https://github.com/MicrosoftDocs/azure-docs/issues/54888) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @darayavah,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/54888.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
