### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Theragus** [MicrosoftDocs/azure-docs.de-de#658]
Link for the Environmental sensor capability model under Create a device template section is broken.
I think it has been moved to :
https://raw.githubusercontent.com/Azure/IoTPlugandPlay/master/samples/EnvironmentalSensor.interface.json
Please update.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a39377ef-57d2-c869-b5bd-4ff711574f5b
* Version Independent ID: 3d741666-8216-0249-342c-ce43cd99c267
* Content: [Tutorial: Verbinden einer generischen Node.js-Client-App mit Azure IoT Central](https://docs.microsoft.com/de-de/azure/iot-central/core/tutorial-connect-device-nodejs?source=docs#create-a-device-template)
* Content Source: [articles/iot-central/core/tutorial-connect-device-nodejs.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-central/core/tutorial-connect-device-nodejs.md)
* Service: **iot-central**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by srvbpigh** [comment]
Hello, @Theragus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54951](https://github.com/MicrosoftDocs/azure-docs/issues/54951) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Theragus, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54951. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
