### ISSUE TITLE
Node is not Knoten in the  context of NodeJS

### ISSUE THREAD

**Issue by DerAlbertCom** [MicrosoftDocs/azure-docs.de-de#66]
e.g. https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/service-bus-relay/relay-hybrid-connections-node-ws-api-overview.md

Leave Node as Node ....

**Comment by SunnyDeng** [comment]
@DerAlbertCom thank you for the feedback. Your request is escalated to the linguistic expert: 
https://ceapex.visualstudio.com/CEINTL/_queries/edit/9391/?triage=true

**Comment by SunnyDeng** [comment]
@DerAlbertCom I got the feedback fixed 2 weeks ago. Please kindly reopen if you see differently. Thanks a lot!
