### ISSUE TITLE
Incorrect PowerShell command

### ISSUE THREAD

**Issue by jdrepo** [MicrosoftDocs/azure-docs.de-de#660]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 10638ad5-51c2-679d-2ac0-356321f750f4
* Version Independent ID: 69e5f565-3e5b-ec02-a424-451a8747b164
* Content: [Überwachen von virtuellen Azure-Computern mit Azure Monitor](https://docs.microsoft.com/de-de/azure/azure-monitor/insights/monitor-vm-azure)
* Content Source: [articles/azure-monitor/insights/monitor-vm-azure.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-monitor/insights/monitor-vm-azure.md)
* Service: **azure-monitor**
* Sub-service: **logs**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by jdrepo** [comment]
Hello,

there is something wring with the PowerShell command at "https://docs.microsoft.com/de-de/azure/azure-monitor/insights/monitor-vm-azure#collect-platform-metrics-and-activity-log"
Seems like am mix between cli and powershell

![2020-05-24 14_56_52-Window](https://user-images.githubusercontent.com/65734789/82754729-3919ba80-9dcf-11ea-8d3f-d2ec754b9864.png)

Set-AzDiagnosticSetting -Name vm-diagnostics -ResourceId "/subscriptions/monitor diagnostic-settings create \
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/my-resource-group/providers/Microsoft.Compute/virtualMachines/my-vm" -Enabled $true -MetricCategory AllMetrics -workspaceId "/subscriptions/monitor diagnostic-settings create \
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/my-resource-group/providers/microsoft.operationalinsights/workspaces/my-workspace"

**Comment by srvbpigh** [comment]
Hello, @jdrepo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55614](https://github.com/MicrosoftDocs/azure-docs/issues/55614) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @jdrepo,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/55614.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
