### ISSUE TITLE
Error: EBUSY: resource busy or locked, write [...]

### ISSUE THREAD

**Issue by zebrassimo** [MicrosoftDocs/azure-docs.de-de#661]
Hi,

after  `sudo node index.js '<YOUR AZURE IOT HUB DEVICE CONNECTION STRING>'`, I get

```
[Device] Using MQTT transport protocol
[Device] Sending message: {"messageId":1,"deviceId":"RKK_Raspi","temperature":29.58324468315664,"humidity":65.7509924180759}
/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/applicationinsights/AutoCollection/Exceptions.js:27
                         throw error;
                         ^
 
Error: EBUSY: resource busy or locked, write
at Object.writeSync (fs.js:573:3)
at Object.writeFileSync (fs.js:1204:26)
at exportGpio (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/onoff/onoff.js:18:8)
at new Gpio (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/onoff/onoff.js:172:36)
at blinkLED (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/index.js:88:17)
at client.sendEvent (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/index.js:44:9)
at safeCallback (/home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/azure-iot-device/lib/internal_client.js:30:9)
at /home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/azure-iot-device/lib/internal_client.js:129:17
at /home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/azure-iot-common/lib/retry_operation.js:57:21
at /home/pi/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp/node_modules/azure-iot-device-mqtt/lib/mqtt.js:399:17
pi@raspberrypi:~/azure-iot-samples-node/iot-hub/Tutorials/RaspberryPiApp $
```
 
 while this is my config.json file
```
{
  "simulatedData": true,
  "interval": 20000,
  "deviceId": "RKK_Raspi",
  "LEDPinGPIO": 24,
  "messageMax": 256,
  "credentialPath": "~/.iot-hub",
  "temperatureAlert": 30,
  "transport": "mqtt",
  "iotEdgeRootCertFilePath": null,
  "i2cOption": {
    "pin": 9,
    "i2cBusNo": 1,
    "i2cAddress": 119
  }
}

```

[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a57d05c9-562c-02a5-7ccd-b1b1bb7c8f0c
* Version Independent ID: 17ee094f-aee3-ca0c-959b-6380e4ea8b89
* Content: [Verbinden von Raspberry Pi mit Azure IoT Hub in der Cloud (Node.js)](https://docs.microsoft.com/de-de/azure/iot-hub/iot-hub-raspberry-pi-kit-node-get-started)
* Content Source: [articles/iot-hub/iot-hub-raspberry-pi-kit-node-get-started.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-hub/iot-hub-raspberry-pi-kit-node-get-started.md)
* Service: **iot-hub**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by srvbpigh** [comment]
Hello, @zebrassimo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @zebrassimo 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team
