### ISSUE TITLE
Projekt

### ISSUE THREAD

**Issue by OliveR4711** [MicrosoftDocs/azure-docs.de-de#663]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 884b5e88-48eb-c3ad-1995-7cd87339783b
* Version Independent ID: e06cfd58-46d0-200a-5967-c6a1a7276997
* Content: [Schnellstart: Verwenden der Anomalieerkennungs-Clientbibliothek - Azure Cognitive Services](https://docs.microsoft.com/de-de/azure/cognitive-services/anomaly-detector/quickstarts/client-libraries?pivots=programming-language-csharp&tabs=windows)
* Content Source: [articles/cognitive-services/Anomaly-Detector/quickstarts/client-libraries.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/cognitive-services/Anomaly-Detector/quickstarts/client-libraries.md)
* Service: **cognitive-services**
* Sub-service: **anomaly-detector**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @OliveR4711
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @OliveR4711

Wir freuen uns über Ihren Kommentar und bemühen uns, Ihre Erfahrungen mit docs.microsoft.com zu verbessern. Wir benötigen jedoch weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern? 

Mit freundlichen Grüßen 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @OliveR4711 
Nochmals vielen Dank für Ihren Kommentar.
Leider fehlen uns immer noch Informationen und wir können Ihr Feedback nicht bearbeiten. Wir schließen dieses GitHub-Problem jetzt, möchten Sie aber ermutigen, in Zukunft weiteres Feedback zu geben.
Mit freundlichen Grüßen
Microsoft DOCS International Team

**Comment by OliveR4711** [comment]
Hallo Cecilia,

um welchen Kommentar geht es denn? Wenn Sie mir den Inhalt nennen, haben wir nach diesem Feiertag Kommunikation.

Mit freundlichen Grüßen

Oliver Reich

________________________________
