### ISSUE TITLE
Deutsche und englische Seite sind inkonsistent.

### ISSUE THREAD

**Issue by mirkogolze** [MicrosoftDocs/azure-docs.de-de#673]
In den deutschen Firewallanforderungen (https://docs.microsoft.com/de-de/azure/azure-monitor/platform/log-analytics-agent#network-requirements) sind 5 Einträge. Ganz am Ende *.azure.com.
In der englischen Variante (https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-analytics-agent#network-requirements) sind es nur 4 Einträge und der letzte, sehr globale Eintrag fehlt.
Bitte die entsprechend fehlerhafte Seit korrigieren. Ich gehe davon aus, dass die deutsche fehlerhaft ist.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6b71519d-1b94-c489-ce51-7210eb05b109
* Version Independent ID: fb6adce7-aa81-28e9-ad54-8c90dd86afa2
* Content: [Übersicht über den Log Analytics-Agent](https://docs.microsoft.com/de-de/azure/azure-monitor/platform/log-analytics-agent#network-requirements)
* Content Source: [articles/azure-monitor/platform/log-analytics-agent.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/azure-monitor/platform/log-analytics-agent.md)
* Sub-service: **logs**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by srvbpigh** [comment]
Hello, @mirkogolze
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Vielen Dank für Ihr Feedback.  

Unsere Technikexperten haben sich Ihre Vorschläge angesehen und für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: https://docs.microsoft.com/de-de/azure/azure-monitor/platform/log-analytics-agent#network-requirements.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
