### ISSUE TITLE
"Azure IoT Edge on Ubuntu virtual machine" Link broken

### ISSUE THREAD

**Issue by ThomasPe** [MicrosoftDocs/azure-docs.de-de#675]
The link to the Azure IoT Edge on Ubuntu VM listed in the prerequisites is going to a 404.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e2289383-6ce2-a036-c710-7d1fad6e1700
* Version Independent ID: 3b902941-0876-17c3-3f0b-a4b7f7770531
* Content: [Schnellstart: Erstellen eines Azure IoT Edge-Geräts unter Linux](https://docs.microsoft.com/de-de/azure/iot-edge/quickstart-linux)
* Content Source: [articles/iot-edge/quickstart-linux.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/iot-edge/quickstart-linux.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by ThomasPe** [comment]
Same for the "IoT Edge Modules section of the Azure Marketplace" Link

**Comment by srvbpigh** [comment]
Hello, @ThomasPe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by kgremban** [comment]
@ThomasPe Can you try again? Both links work for me currently, so hopefully it was a temporary glitch.

**Comment by ThomasPe** [comment]
It seems the link only doesn't work for me in the Chromium-based Edge, Chrome & IE11 works fine. 🤔

**Comment by CeciAc** [comment]
Hello, @ThomasPe 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
