### ISSUE TITLE
How to register Integration runtime node via dmgcmd with Proxy?

### ISSUE THREAD

**Issue by eXXL** [MicrosoftDocs/azure-docs.de-de#677]
I want to automate the registration of a Self-Hosted Integration Runtime Node at a Data Factory using the command dmgcmd as described in the linked article.

I have to set a proxy. How can I achieve this? Is there a parameter to set a custom proxy? Or do I have to select System Proxy and modify the config files before?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 32785d15-8202-6e44-f1d2-420ef0600f3f
* Version Independent ID: 3af5fa49-7bd4-18ce-f8dc-aa4a2b8c6478
* Content: [Erstellen einer selbstgehosteten Integration Runtime](https://docs.microsoft.com/de-de/azure/data-factory/create-self-hosted-integration-runtime)
* Content Source: [articles/data-factory/create-self-hosted-integration-runtime.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/data-factory/create-self-hosted-integration-runtime.md)
* Service: **data-factory**
* GitHub Login: @nabhishek
* Microsoft Alias: **abnarain**

**Comment by srvbpigh** [comment]
Hello, @eXXL
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #56406](https://github.com/MicrosoftDocs/azure-docs/issues/56406) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @eXXL, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/56406. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
