### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by PaulTiffert** [MicrosoftDocs/azure-docs.de-de#679]

**Comment by PaulTiffert** [comment]
Hello, sorry for the late reply and the inconvenience, so unfortunately I am new in this business and situated in Europe. This issue has been opened by me by mistake.

**Comment by CeciAc** [comment]
Hello, @PaulTiffert 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
