### ISSUE TITLE
SQLState = 08001, NativeError = 53

### ISSUE THREAD

**Issue by Armin-FB** [MicrosoftDocs/azure-docs.de-de#68]
Hi,

i'm trying to import data to my azure sql database via a csv-file like that:

```
$bcp = "bcp $tableName in $fileName -S $database -d $serverFQDN -U $adminName -P $adminPassword -q -c -t"
invoke-Expression $bcp

```

But I'm keep getting this error-message:

SQLState = 08001, NativeError = 53
Error = [Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.

I managed to create tables via powershellscript (without bcp/sqlmcd), which is why I don't understand why I can't connect to the server when I use BCP.

any suggestions? 

best regards!

**Comment by SunnyDeng** [comment]
@craigg-msft HI Craig, could you please help him? Or find the right owner for the help?

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #5420](https://github.com/MicrosoftDocs/azure-docs/issues/5420) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Moved to the en-us repo
https://github.com/MicrosoftDocs/azure-docs/issues/5420
