### ISSUE TITLE
Wrong supported account types

### ISSUE THREAD

**Issue by Fastor01** [MicrosoftDocs/azure-docs.de-de#680]
Point 6 under "Register a web applikation" (not legacy) describes the wrong supported account types. On my AAD B2C the userflow only works when selecting "Accounts in any organizational directory or any identity provider. For authenticating users with Azure AD B2C."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 670bf490-966b-e72e-ab6c-1d189f9a1f58
* Version Independent ID: a55b7372-87e9-c760-1a37-57728171395d
* Content: [Tutorial: Registrieren einer Anwendung - Azure AD B2C](https://docs.microsoft.com/de-de/azure/active-directory-b2c/tutorial-register-applications?tabs=app-reg-ga)
* Content Source: [articles/active-directory-b2c/tutorial-register-applications.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory-b2c/tutorial-register-applications.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by srvbpigh** [comment]
Hello, @Fastor01
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #57164](https://github.com/MicrosoftDocs/azure-docs/issues/57164) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hallo, @Fastor01,  

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation.  

Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/azure-docs/issues/57164.  

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.   

Mit freundlichen Grüßen  
das Microsoft DOCS International Team
