### ISSUE TITLE
Data profile and preview: Docs for dataset profile is not up to date

### ISSUE THREAD

**Issue by BMeyn** [MicrosoftDocs/azure-docs.de-de#728]
Hello,

I searched for a description for the columns in the datasets profile. I found something at the following [Link](https://docs.microsoft.com/de-de/azure/machine-learning/how-to-connect-data-ui#data-profile-and-preview).

The description for the "Error Count" and  "Empty Count" is missing here. 

How does the "Error Count" work? Are there special stings or values that treated as errors? 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e7caf9eb-e066-3da0-1874-fac2d917ea8f
* Version Independent ID: 924415cd-8e14-c48a-705d-c6b37145b456
* Content: [Herstellen einer Verbindung mit Daten in Speicherdiensten in Azure - Azure Machine Learning](https://docs.microsoft.com/de-de/azure/machine-learning/how-to-connect-data-ui#data-profile-and-preview)
* Content Source: [articles/machine-learning/how-to-connect-data-ui.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/machine-learning/how-to-connect-data-ui.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @nibaccam
* Microsoft Alias: **nibaccam**

**Comment by nibaccam** [comment]
Hi @BMeyn  thank you for your question. I've reached out to the product team for additional details.

**Comment by nibaccam** [comment]
Hi @BMeyn Error Count is for instances when a specific type conversion of a column fails. 

Strings like, NaN. null, NaT etc are considered missing values which are considered in the Empty Count.

**Comment by nibaccam** [comment]
We will now proceed to close this thread. 
#please-close

**Comment by nibaccam** [comment]
@BMeyn please close this issue when you are able. 
Thanks! :)

**Comment by PeterCLu** [comment]
#plesae-close

**Comment by PeterCLu** [comment]
#please-close
