### ISSUE TITLE
What are Protected risky sign-in detections

### ISSUE THREAD

**Issue by gunterda** [MicrosoftDocs/azure-docs.de-de#733]
In the pictures on the page, you show in the risky sign-in detections a number for "Protected". What does this "Protected" mean. I don't find any reference to "Protected" on this page. So, what does "Protected" stand for? When I click on the number of "Protected" I get the same list as when I click on "Unprotected" so I have on way to figure out which of the sign-ins were "Protected" So why do you display this "Protected" number?
Thank you for your feedback.
Gunter

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 81a1385f-b90a-e7b4-8cbd-f25aeb8b3c49
* Version Independent ID: d468eb75-88a9-b1aa-7fb3-19ebb4faa179
* Content: [Was bedeutet Risiko? Azure AD Identity Protection](https://docs.microsoft.com/de-de/azure/active-directory/identity-protection/concept-identity-protection-risks)
* Content Source: [articles/active-directory/identity-protection/concept-identity-protection-risks.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/identity-protection/concept-identity-protection-risks.md)
* Service: **active-directory**
* Sub-service: **identity-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@gunterda I am not sure what you are referring to but I think it is the protected/unprotected box on the overview. This is showing where sign in events did not go through a policy that triggers controls like multi-factor authentication based on risk.

**Comment by MicrosoftGuyJFlo** [comment]
#assign @MicrosoftGuyJFlo

**Comment by gunterda** [comment]
@MicrosoftGuyJFlo Thank you for the update on this. "This is showing where sign in events did not go through a policy that triggers controls like multi-factor authentication based on risk." -> ok, now I know what it means. That makes sence. Thank you.

**Comment by gunterda** [comment]
It's clear now.
