### ISSUE TITLE
InResponseTo Error on when you try to login

### ISSUE THREAD

**Issue by mbrode** [MicrosoftDocs/azure-docs.de-de#745]
Hey there, 

followed your introduction and installed successfully SSO for Confluence. 
But if you clock on the login button for the SSO Login you get the error "InResponseTo of the response does not match the ID of the authentication request. Please try again."
If you click afterwards again on the login button it works. How can we fix that? 

Also cause you miss the link what you want to open in Confluence. If you click from somewhere on a link where the target is a a Confluence page and you hit the "InResponseTo" Error you loose your target page. 

Thanks
Michael

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a45acbc6-caae-be6c-939e-55451831d03e
* Version Independent ID: 0d88f4ee-2ac5-1ad4-245b-b8c0752a7303
* Content: [Tutorial: Integration des einmaligen Anmeldens von Azure Active Directory mit Confluence SAML SSO by Microsoft](https://docs.microsoft.com/de-de/azure/active-directory/saas-apps/confluencemicrosoft-tutorial)
* Content Source: [articles/active-directory/saas-apps/confluencemicrosoft-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/active-directory/saas-apps/confluencemicrosoft-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by jeevansd** [comment]
@mbrode Can you please send this issue to me on this email AADSpecialIntegrationSupport <AADSpecialIntegrationSupport@service.microsoft.com>

**Comment by mbrode** [comment]
@jeevansd Will do. Thanks.
