### ISSUE TITLE
Mismatch with temp storage declaration for B-Series Standard B1s machines

### ISSUE THREAD

**Issue by DaKarli** [MicrosoftDocs/azure-docs.de-de#79]
On this page it is stated that a B1s machine gets a temp storage of 4 GB but on the pricing page https://azure.microsoft.com/de-de/pricing/details/virtual-machines/windows/
it states that this machine only gets 2 GB of temp storage.
So one of these statements must be wrong.

Ragards, Harry.

**Comment by CeciAc** [comment]
Hello, @DaKarli.
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @DaKarli 
We need further clarification to work on this issue.
Can you please provide the URL of the page where you saw this inconsistency?
Thank you in advance, 

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @DaKarli
We cannot process this issue with the provided information so we are closing it.
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
Feel free to create a new issue if the problem persists.

Thank you in advance,

Kind regards,
Microsoft DOCS International Team
@SunnyDeng

**Comment by SunnyDeng** [comment]
@DaKarli in case you see this message. If you may provide the URL of the page where you saw the information "... stated that a B1s machine gets a temp storage of 4 GB", then it will help us to identify your issue accurately. 
This issue will be continously supported if you provide the URL and clich 'Reopen and comment' button. 
Thanks for your support!
-sunny

**Comment by DaKarli** [comment]
Hi Sunny and Ceci,
sorry for my late reply.
The mentioned mismatches for all languages can be found between the pricing page:

[(https://azure.microsoft.com/de-de/pricing/details/virtual-machines/windows/)]

and these pages:

[https://docs.microsoft.com/de-de/azure/virtual-machines/windows/b-series-burstable]
[https://docs.microsoft.com/de-de/azure/virtual-machines/windows/sizes-general]

Hope you have all necessary information now.
Regards, Harry.
