### ISSUE TITLE
das Löschen der Historie sollte implementiert werden, auch sollte der jeweils verbrauchte Speicherplatz angezeigt werden

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/azure-docs.de-de#80]
Da ständig die Meldung kommt, dass man über 10 GB verbraucht hat und daher nichts mehr speichern oder gar ausführen kann, wäre es sehr hilfreich:
- wenn die Speicherplatz Verwendung von Experimenten und Einträgen in der Historie angezeigt wird
- wenn man Historien vollständig löschen könnte
- wenn man aus Historien die Daten gelöscht bekäme, so dass zwar die Einstellungen noch da sind, man das Experiment also mit den Einstellungen wiederholen könnte

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7d8b5a4c-72cb-7629-b23c-a7a9a4ef7a17
* Version Independent ID: 4a2d1eb6-81d6-a765-a678-203124549e96
* Content: [Verwalten von Experimentiterationen in Azure Machine Learning-Studio](https://docs.microsoft.com/de-de/azure/machine-learning/studio/manage-experiment-iterations)
* Content Source: [articles/machine-learning/studio/manage-experiment-iterations.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/machine-learning/studio/manage-experiment-iterations.md)
* Service: **machine-learning**
* Product: **unspecified**
* GitHub Login: @heatherbshapiro
* Microsoft Alias: **hshapiro**

**Comment by CeciAc** [comment]
Hallo, @heatherbshapiro 

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team 

@SunnyDeng
