### ISSUE TITLE
Wrong path to x11 config

### ISSUE THREAD

**Issue by bolausson** [MicrosoftDocs/azure-docs.de-de#83]
Hej,

I would like propose an updated version of the script to update the BUSID in the X11 config file which in most cases is now in /etc/X11/xorg.conf and no longer in /etc/X11/XF86Config.

furthermore it is more straight forward to get the BusID via
```
nvidia-xconfig --query-gpu-info | awk '/PCI BusID/{print $4}'
```
instead of
```
echo $((16#`/usr/bin/nvidia-smi --query-gpu=pci.bus_id --format=csv | tail -1 | cut -d ':' -f 1`))
```

All wrapped up:
```bash
#!/bin/bash
#
#
#
XCONFIG="/etc/X11/xorg.conf"

OLDBUSID=`awk '/BusID/{gsub(/"/, "", $2); print $2}' ${XCONFIG}`
NEWBUSID=`nvidia-xconfig --query-gpu-info | awk '/PCI BusID/{print $4}'`

if [[ "${OLDBUSID}" == "${NEWBUSID}" ]] ; then
        echo "NVIDIA BUSID not changed - nothing to do"
else
        echo "NVIDIA BUSID changed from \"${OLDBUSID}\" to \"${NEWBUSID}\": Updating ${XCONFIG}" 
        sed -e 's|BusID.*|BusID          '\"${NEWBUSID}\"'|' -i ${XCONFIG}
fi
```
Greetings,
Bjoern

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0e03790a-1bf9-146d-704b-6816d475064b
* Version Independent ID: ad5f6be7-e089-161f-306c-39d10e7ab0a0
* Content: [Einrichtung von Treibern für die Azure N-Serie unter Linux](https://docs.microsoft.com/de-de/azure/virtual-machines/linux/n-series-driver-setup)
* Content Source: [articles/virtual-machines/linux/n-series-driver-setup.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/virtual-machines/linux/n-series-driver-setup.md)
* Service: **virtual-machines-linux**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by CeciAc** [comment]
Hello, @bolausson,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here https://github.com/MicrosoftDocs/azure-docs/issues/9872.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
