### ISSUE TITLE
German Translation wrong. "Es gibt wichtige und behutsame Unterschiede" must be "Es gibt wichtige und wohl durchdachte Unterschiede"

### ISSUE THREAD

**Issue by thomasschoenemeyer** [MicrosoftDocs/azure-docs.de-de#84]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7eaaf7c7-c1fe-1afc-e7f8-bc0e90044fb8
* Version Independent ID: 6461936a-3f5d-c2fe-cb37-e40fc9dc929e
* Content: [Übersicht über Azure Load Balancer](https://docs.microsoft.com/de-de/azure/load-balancer/load-balancer-overview)
* Content Source: [articles/load-balancer/load-balancer-overview.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/load-balancer/load-balancer-overview.md)
* Service: **load-balancer**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by LisandroSu** [comment]
Hallo, @thomasschoenemeyer , 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hallo, @thomasschoenemeyer 

   

Vielen Dank für Ihr Feedback.  

unsere Sprachexperten haben sich Ihren Vorschlag angesehen und diesen für gut befunden. Wir haben Ihr Feedback implementiert und im aktualisierten Artikel auf der Dokumentationsseite unter folgender Seite veröffentlicht: XXX.   

Vielen Dank für Ihren Beitrag zu diesem Artikel. Gerne können Sie auch weiterhin Feedback zu anderen Artikeln abgeben.  

 

Mit freundlichen Grüßen  

das Microsoft DOCS International Team
