### ISSUE TITLE
Public IP wird nicht zugewiesen. 

### ISSUE THREAD

**Issue by borstibacon** [MicrosoftDocs/azure-docs.de-de#85]
Guten Tag,

beim Ausführen der Anwendung werden die Services und Deployments korrekt und ohne Fehler ausgeführt.
Es wird jedoch keine public IP zugewiesen.  
Der Status bleibt auch nach einem Tag auf &lt;pending&gt;.
Ein Löschen und erneutes ausführen hat nicht geholfen. 
Erstellt wurde das Cluster über das Portal.

Ist das ein bekannter Fehler?

Gruß 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 965a7faf-6684-1b1e-3570-ea0b38ce02db
* Version Independent ID: 2efd8393-0b5b-e827-8762-fa58d6758d93
* Content: [Schnellstart – Schnellstart für Azure Kubernetes-Cluster im Portal](https://docs.microsoft.com/de-de/azure/aks/kubernetes-walkthrough-portal)
* Content Source: [articles/aks/kubernetes-walkthrough-portal.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/live/articles/aks/kubernetes-walkthrough-portal.md)
* Service: **container-service**
* GitHub Login: @neilpeterson
* Microsoft Alias: **nepeters**

**Comment by CeciAc** [comment]
Hallo, @borstibacon

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team
